export const BACKGROUND_LABELS: Record<string, Record<string, string>> = {
  "en": {
    "paper": "Paper",
    "midnight": "Midnight",
    "forest": "Forest",
    "ocean": "Ocean",
    "rose": "Rose",
    "lavender": "Lavender",
    "mint": "Mint",
    "sand": "Sand",
    "charcoal": "Charcoal",
    "sky": "Sky",
    "coffee": "Coffee",
    "grape": "Grape",
    "sunset": "Sunset",
    "ice": "Ice",
    "ink": "Ink"
  },
  "ru": {
    "paper": "Бумага",
    "midnight": "Полночь",
    "forest": "Лес",
    "ocean": "Океан",
    "rose": "Роза",
    "lavender": "Лаванда",
    "mint": "Мята",
    "sand": "Песок",
    "charcoal": "Графит",
    "sky": "Небо",
    "coffee": "Кофе",
    "grape": "Виноград",
    "sunset": "Закат",
    "ice": "Лёд",
    "ink": "Чернила"
  },
  "es": {
    "paper": "papel",
    "midnight": "medianoche",
    "forest": "bosque",
    "ocean": "océano",
    "rose": "rosa",
    "lavender": "lavanda",
    "mint": "menta",
    "sand": "Arena",
    "charcoal": "carbón",
    "sky": "cielo",
    "coffee": "cafe",
    "grape": "uva",
    "sunset": "puesta de sol",
    "ice": "Hielo",
    "ink": "tinta"
  },
  "zh": {
    "paper": "纸",
    "midnight": "午夜",
    "forest": "森林",
    "ocean": "海洋",
    "rose": "玫瑰",
    "lavender": "薰衣草",
    "mint": "薄荷",
    "sand": "沙子",
    "charcoal": "木炭",
    "sky": "天空",
    "coffee": "咖啡",
    "grape": "葡萄",
    "sunset": "日落",
    "ice": "冰",
    "ink": "墨水"
  },
  "hi": {
    "paper": "कागज",
    "midnight": "आधी रात",
    "forest": "वन",
    "ocean": "सागर",
    "rose": "गुलाब",
    "lavender": "लैवेंडर",
    "mint": "पुदीना",
    "sand": "रेत",
    "charcoal": "लकड़ी का कोयला",
    "sky": "आकाश",
    "coffee": "कॉफ़ी",
    "grape": "अंगूर",
    "sunset": "सूर्यास्त",
    "ice": "बर्फ",
    "ink": "स्याही"
  },
  "ar": {
    "paper": "ورق",
    "midnight": "منتصف الليل",
    "forest": "غابة",
    "ocean": "المحيط",
    "rose": "روز",
    "lavender": "لافندر",
    "mint": "نعناع",
    "sand": "الرمال",
    "charcoal": "فحم",
    "sky": "السماء",
    "coffee": "قهوة",
    "grape": "العنب",
    "sunset": "غروب الشمس",
    "ice": "الجليد",
    "ink": "حبر"
  },
  "pt": {
    "paper": "Papel",
    "midnight": "Meia-noite",
    "forest": "Floresta",
    "ocean": "Oceano",
    "rose": "Rosa",
    "lavender": "Lavanda",
    "mint": "Menta",
    "sand": "Areia",
    "charcoal": "Carvão",
    "sky": "Céu",
    "coffee": "Café",
    "grape": "Uva",
    "sunset": "Pôr do sol",
    "ice": "Gelo",
    "ink": "Tinta"
  },
  "bn": {
    "paper": "কাগজ",
    "midnight": "মধ্যরাত",
    "forest": "বন",
    "ocean": "মহাসাগর",
    "rose": "গোলাপ",
    "lavender": "ল্যাভেন্ডার",
    "mint": "পুদিনা",
    "sand": "বালি",
    "charcoal": "কাঠকয়লা",
    "sky": "আকাশ",
    "coffee": "কফি",
    "grape": "আঙ্গুর",
    "sunset": "সূর্যাস্ত",
    "ice": "বরফ",
    "ink": "কালি"
  },
  "fr": {
    "paper": "Papier",
    "midnight": "Minuit",
    "forest": "Forêt",
    "ocean": "Océan",
    "rose": "Rose",
    "lavender": "Lavande",
    "mint": "Menthe",
    "sand": "Sable",
    "charcoal": "Charbon de bois",
    "sky": "Ciel",
    "coffee": "Café",
    "grape": "Raisin",
    "sunset": "Coucher de soleil",
    "ice": "Glace",
    "ink": "Encre"
  },
  "de": {
    "paper": "Papier",
    "midnight": "Mitternacht",
    "forest": "Wald",
    "ocean": "Ozean",
    "rose": "Rose",
    "lavender": "Lavendel",
    "mint": "Minze",
    "sand": "Sand",
    "charcoal": "Kohle",
    "sky": "Himmel",
    "coffee": "Kaffee",
    "grape": "Traube",
    "sunset": "Sonnenuntergang",
    "ice": "Eis",
    "ink": "Tinte"
  },
  "ja": {
    "paper": "紙",
    "midnight": "真夜中",
    "forest": "森",
    "ocean": "オーシャン",
    "rose": "ローズ",
    "lavender": "ラベンダー",
    "mint": "ミント",
    "sand": "砂",
    "charcoal": "木炭",
    "sky": "空",
    "coffee": "コーヒー",
    "grape": "ぶどう",
    "sunset": "日没",
    "ice": "氷",
    "ink": "インク"
  },
  "ko": {
    "paper": "종이",
    "midnight": "자정",
    "forest": "숲",
    "ocean": "바다",
    "rose": "장미",
    "lavender": "라벤더",
    "mint": "민트",
    "sand": "모래",
    "charcoal": "숯",
    "sky": "하늘",
    "coffee": "커피",
    "grape": "포도",
    "sunset": "일몰",
    "ice": "얼음",
    "ink": "잉크"
  },
  "tr": {
    "paper": "Kağıt",
    "midnight": "Gece yarısı",
    "forest": "Orman",
    "ocean": "Okyanus",
    "rose": "Gül",
    "lavender": "lavanta",
    "mint": "Nane",
    "sand": "Kum",
    "charcoal": "Kömür",
    "sky": "Gökyüzü",
    "coffee": "Kahve",
    "grape": "Üzüm",
    "sunset": "Gün batımı",
    "ice": "Buz",
    "ink": "Mürekkep"
  },
  "it": {
    "paper": "Carta",
    "midnight": "Mezzanotte",
    "forest": "Foresta",
    "ocean": "Oceano",
    "rose": "Rosa",
    "lavender": "Lavanda",
    "mint": "Menta",
    "sand": "Sabbia",
    "charcoal": "Carbone",
    "sky": "Cielo",
    "coffee": "Caffè",
    "grape": "Uva",
    "sunset": "Tramonto",
    "ice": "Ghiaccio",
    "ink": "Inchiostro"
  },
  "pl": {
    "paper": "Papier",
    "midnight": "Północ",
    "forest": "Las",
    "ocean": "Ocean",
    "rose": "Róża",
    "lavender": "Lawenda",
    "mint": "Mięta",
    "sand": "Piasek",
    "charcoal": "Węgiel drzewny",
    "sky": "Niebo",
    "coffee": "Kawa",
    "grape": "Winogrono",
    "sunset": "Zachód słońca",
    "ice": "Lód",
    "ink": "Atrament"
  },
  "uk": {
    "paper": "Папір",
    "midnight": "опівночі",
    "forest": "Ліс",
    "ocean": "океан",
    "rose": "Роза",
    "lavender": "Лаванда",
    "mint": "Монетний двір",
    "sand": "Пісок",
    "charcoal": "Деревне вугілля",
    "sky": "небо",
    "coffee": "кава",
    "grape": "виноград",
    "sunset": "Захід сонця",
    "ice": "лід",
    "ink": "Чорнило"
  },
  "nl": {
    "paper": "Papier",
    "midnight": "Middernacht",
    "forest": "Bos",
    "ocean": "Oceaan",
    "rose": "Roos",
    "lavender": "Lavendel",
    "mint": "Munt",
    "sand": "Zand",
    "charcoal": "Houtskool",
    "sky": "Hemel",
    "coffee": "Koffie",
    "grape": "Druif",
    "sunset": "Zonsondergang",
    "ice": "IJs",
    "ink": "Inkt"
  },
  "id": {
    "paper": "Kertas",
    "midnight": "Tengah malam",
    "forest": "Hutan",
    "ocean": "Lautan",
    "rose": "Mawar",
    "lavender": "warna lembayung muda",
    "mint": "daun mint",
    "sand": "Pasir",
    "charcoal": "Arang",
    "sky": "Langit",
    "coffee": "Kopi",
    "grape": "Anggur",
    "sunset": "Matahari terbenam",
    "ice": "Es",
    "ink": "Tinta"
  },
  "vi": {
    "paper": "Giấy",
    "midnight": "Nửa đêm",
    "forest": "Rừng",
    "ocean": "đại dương",
    "rose": "hoa hồng",
    "lavender": "hoa oải hương",
    "mint": "bạc hà",
    "sand": "Cát",
    "charcoal": "than củi",
    "sky": "bầu trời",
    "coffee": "cà phê",
    "grape": "nho",
    "sunset": "Hoàng hôn",
    "ice": "băng",
    "ink": "Mực"
  },
  "th": {
    "paper": "กระดาษ",
    "midnight": "เที่ยงคืน",
    "forest": "ป่า",
    "ocean": "มหาสมุทร",
    "rose": "โรส",
    "lavender": "ลาเวนเดอร์",
    "mint": "มิ้นต์",
    "sand": "ทราย",
    "charcoal": "ถ่าน",
    "sky": "ท้องฟ้า",
    "coffee": "กาแฟ",
    "grape": "องุ่น",
    "sunset": "พระอาทิตย์ตก",
    "ice": "น้ำแข็ง",
    "ink": "หมึก"
  },
  "fa": {
    "paper": "کاغذ",
    "midnight": "نیمه شب",
    "forest": "جنگل",
    "ocean": "اقیانوس",
    "rose": "رز",
    "lavender": "اسطوخودوس",
    "mint": "نعناع",
    "sand": "شن و ماسه",
    "charcoal": "زغال چوب",
    "sky": "آسمان",
    "coffee": "قهوه",
    "grape": "انگور",
    "sunset": "غروب آفتاب",
    "ice": "یخ",
    "ink": "جوهر"
  },
  "ur": {
    "paper": "کاغذ",
    "midnight": "آدھی رات",
    "forest": "جنگل",
    "ocean": "سمندر",
    "rose": "گلاب",
    "lavender": "لیوینڈر",
    "mint": "پودینہ",
    "sand": "ریت",
    "charcoal": "چارکول",
    "sky": "آسمان",
    "coffee": "کافی",
    "grape": "انگور",
    "sunset": "غروب آفتاب",
    "ice": "برف",
    "ink": "سیاہی"
  },
  "ms": {
    "paper": "kertas",
    "midnight": "tengah malam",
    "forest": "Hutan",
    "ocean": "Lautan",
    "rose": "Mawar",
    "lavender": "Lavender",
    "mint": "Pudina",
    "sand": "pasir",
    "charcoal": "arang",
    "sky": "Langit",
    "coffee": "kopi",
    "grape": "Anggur",
    "sunset": "matahari terbenam",
    "ice": "ais",
    "ink": "Dakwat"
  },
  "fil": {
    "paper": "Papel",
    "midnight": "hatinggabi",
    "forest": "kagubatan",
    "ocean": "Karagatan",
    "rose": "Rose",
    "lavender": "Lavender",
    "mint": "Mint",
    "sand": "buhangin",
    "charcoal": "Uling",
    "sky": "Sky",
    "coffee": "kape",
    "grape": "Ubas",
    "sunset": "Paglubog ng araw",
    "ice": "yelo",
    "ink": "tinta"
  },
  "ro": {
    "paper": "Hârtie",
    "midnight": "Miezul nopții",
    "forest": "pădure",
    "ocean": "Ocean",
    "rose": "Trandafir",
    "lavender": "Lavandă",
    "mint": "Mentă",
    "sand": "Nisip",
    "charcoal": "Cărbune",
    "sky": "cerul",
    "coffee": "cafea",
    "grape": "Strugurii",
    "sunset": "Apus de soare",
    "ice": "Gheață",
    "ink": "Cerneală"
  },
  "cs": {
    "paper": "Papír",
    "midnight": "Půlnoc",
    "forest": "Les",
    "ocean": "oceán",
    "rose": "Růže",
    "lavender": "Levandule",
    "mint": "máta",
    "sand": "Písek",
    "charcoal": "Dřevěné uhlí",
    "sky": "nebe",
    "coffee": "Káva",
    "grape": "Hroznová",
    "sunset": "Západ slunce",
    "ice": "led",
    "ink": "Inkoust"
  },
  "el": {
    "paper": "χαρτί",
    "midnight": "Μεσάνυχτα",
    "forest": "Δάσος",
    "ocean": "Ωκεανός",
    "rose": "Τριαντάφυλλο",
    "lavender": "Λεβάντα",
    "mint": "Μέντα",
    "sand": "Άμμος",
    "charcoal": "κάρβουνο",
    "sky": "Ουρανός",
    "coffee": "Καφές",
    "grape": "σταφύλι",
    "sunset": "Ηλιοβασίλεμα",
    "ice": "Πάγος",
    "ink": "Μελάνι"
  },
  "sv": {
    "paper": "Papper",
    "midnight": "Midnatt",
    "forest": "Skog",
    "ocean": "Ocean",
    "rose": "Rose",
    "lavender": "Lavendel",
    "mint": "Mynta",
    "sand": "Sand",
    "charcoal": "Träkol",
    "sky": "Sky",
    "coffee": "Kaffe",
    "grape": "Druva",
    "sunset": "Solnedgång",
    "ice": "Is",
    "ink": "Bläck"
  },
  "hu": {
    "paper": "Papír",
    "midnight": "Éjfél",
    "forest": "Erdő",
    "ocean": "Óceán",
    "rose": "Rose",
    "lavender": "Levendula",
    "mint": "Menta",
    "sand": "Homok",
    "charcoal": "Faszén",
    "sky": "Égbolt",
    "coffee": "Kávé",
    "grape": "Szőlő",
    "sunset": "Naplemente",
    "ice": "Jég",
    "ink": "Tinta"
  },
  "he": {
    "paper": "נייר",
    "midnight": "חצות",
    "forest": "יער",
    "ocean": "אוקיינוס",
    "rose": "ורד",
    "lavender": "לבנדר",
    "mint": "מנטה",
    "sand": "חול",
    "charcoal": "פחם",
    "sky": "שמיים",
    "coffee": "קפה",
    "grape": "ענבים",
    "sunset": "שקיעה",
    "ice": "קרח",
    "ink": "דיו"
  },
  "da": {
    "paper": "Papir",
    "midnight": "Midnat",
    "forest": "Skov",
    "ocean": "Ocean",
    "rose": "Rose",
    "lavender": "Lavendel",
    "mint": "Mynte",
    "sand": "Sand",
    "charcoal": "Trækul",
    "sky": "Himmel",
    "coffee": "Kaffe",
    "grape": "Drue",
    "sunset": "Solnedgang",
    "ice": "Is",
    "ink": "Blæk"
  },
  "fi": {
    "paper": "Paperi",
    "midnight": "Keskiyö",
    "forest": "Metsä",
    "ocean": "Ocean",
    "rose": "Rose",
    "lavender": "Laventeli",
    "mint": "Minttu",
    "sand": "Hiekka",
    "charcoal": "Puuhiiltä",
    "sky": "Sky",
    "coffee": "Kahvi",
    "grape": "Rypäle",
    "sunset": "Auringonlasku",
    "ice": "Jäätä",
    "ink": "Muste"
  },
  "no": {
    "paper": "Papir",
    "midnight": "Midnatt",
    "forest": "Skog",
    "ocean": "Ocean",
    "rose": "Rose",
    "lavender": "Lavendel",
    "mint": "Mynte",
    "sand": "Sand",
    "charcoal": "Kull",
    "sky": "Himmel",
    "coffee": "Kaffe",
    "grape": "Drue",
    "sunset": "Solnedgang",
    "ice": "Is",
    "ink": "Blekk"
  },
  "sk": {
    "paper": "Papier",
    "midnight": "Polnoc",
    "forest": "les",
    "ocean": "oceán",
    "rose": "Rose",
    "lavender": "Levanduľa",
    "mint": "Mincovňa",
    "sand": "Piesok",
    "charcoal": "Drevené uhlie",
    "sky": "Sky",
    "coffee": "Káva",
    "grape": "Hrozno",
    "sunset": "Západ slnka",
    "ice": "Ľad",
    "ink": "Atrament"
  },
  "bg": {
    "paper": "Хартия",
    "midnight": "Полунощ",
    "forest": "гора",
    "ocean": "океан",
    "rose": "Роза",
    "lavender": "Лавандула",
    "mint": "Мента",
    "sand": "Пясък",
    "charcoal": "дървени въглища",
    "sky": "небе",
    "coffee": "кафе",
    "grape": "грозде",
    "sunset": "Залез",
    "ice": "Лед",
    "ink": "Мастило"
  },
  "sr": {
    "paper": "Папир",
    "midnight": "Поноћ",
    "forest": "Форест",
    "ocean": "Оцеан",
    "rose": "Росе",
    "lavender": "Лаванда",
    "mint": "Минт",
    "sand": "Песак",
    "charcoal": "Дрвени угаљ",
    "sky": "Небо",
    "coffee": "кафу",
    "grape": "Грожђе",
    "sunset": "Залазак сунца",
    "ice": "Ице",
    "ink": "Инк"
  },
  "hr": {
    "paper": "Papir",
    "midnight": "Ponoć",
    "forest": "šuma",
    "ocean": "Ocean",
    "rose": "Ruža",
    "lavender": "Lavanda",
    "mint": "Kovnica",
    "sand": "pijesak",
    "charcoal": "Drveni ugljen",
    "sky": "Nebo",
    "coffee": "kava",
    "grape": "Grožđe",
    "sunset": "Zalazak sunca",
    "ice": "led",
    "ink": "Tinta"
  },
  "lt": {
    "paper": "Popierius",
    "midnight": "Vidurnaktis",
    "forest": "Miškas",
    "ocean": "Vandenynas",
    "rose": "Rožė",
    "lavender": "Levandos",
    "mint": "Mėtų",
    "sand": "Smėlis",
    "charcoal": "Anglis",
    "sky": "Dangus",
    "coffee": "Kava",
    "grape": "Vynuogė",
    "sunset": "Saulėlydis",
    "ice": "Ledas",
    "ink": "Rašalas"
  },
  "lv": {
    "paper": "Papīrs",
    "midnight": "Pusnakts",
    "forest": "Mežs",
    "ocean": "Okeāns",
    "rose": "Roze",
    "lavender": "Lavanda",
    "mint": "Piparmētra",
    "sand": "Smiltis",
    "charcoal": "Ogles",
    "sky": "Debesis",
    "coffee": "Kafija",
    "grape": "Vīnogas",
    "sunset": "Saulriets",
    "ice": "Ledus",
    "ink": "Tinte"
  },
  "et": {
    "paper": "Paber",
    "midnight": "Kesköö",
    "forest": "Mets",
    "ocean": "Ookean",
    "rose": "Roos",
    "lavender": "Lavendel",
    "mint": "Mint",
    "sand": "Liiv",
    "charcoal": "Süsi",
    "sky": "Taevas",
    "coffee": "Kohv",
    "grape": "Viinamari",
    "sunset": "Päikeseloojang",
    "ice": "Jää",
    "ink": "Tint"
  },
  "sl": {
    "paper": "Papir",
    "midnight": "Polnoč",
    "forest": "Gozd",
    "ocean": "Ocean",
    "rose": "Rose",
    "lavender": "sivka",
    "mint": "Kovnica",
    "sand": "Pesek",
    "charcoal": "Oglje",
    "sky": "Nebo",
    "coffee": "kava",
    "grape": "Grozdje",
    "sunset": "sončni zahod",
    "ice": "Led",
    "ink": "Črnilo"
  },
  "ca": {
    "paper": "Paper",
    "midnight": "Mitjanit",
    "forest": "Bosc",
    "ocean": "Oceà",
    "rose": "Rosa",
    "lavender": "Lavanda",
    "mint": "Menta",
    "sand": "Sorra",
    "charcoal": "Carbó vegetal",
    "sky": "Cel",
    "coffee": "Cafè",
    "grape": "Raïm",
    "sunset": "Posta de sol",
    "ice": "Gel",
    "ink": "Tinta"
  },
  "sw": {
    "paper": "Karatasi",
    "midnight": "Usiku wa manane",
    "forest": "Msitu",
    "ocean": "Bahari",
    "rose": "Rose",
    "lavender": "Lavender",
    "mint": "Minti",
    "sand": "Mchanga",
    "charcoal": "Mkaa",
    "sky": "Anga",
    "coffee": "Kahawa",
    "grape": "Zabibu",
    "sunset": "Machweo",
    "ice": "Barafu",
    "ink": "Wino"
  },
  "ta": {
    "paper": "காகிதம்",
    "midnight": "நள்ளிரவு",
    "forest": "காடு",
    "ocean": "பெருங்கடல்",
    "rose": "ரோஜா",
    "lavender": "லாவெண்டர்",
    "mint": "புதினா",
    "sand": "மணல்",
    "charcoal": "கரி",
    "sky": "வானம்",
    "coffee": "காபி",
    "grape": "திராட்சை",
    "sunset": "சூரிய அஸ்தமனம்",
    "ice": "பனிக்கட்டி",
    "ink": "மை"
  },
  "te": {
    "paper": "పేపర్",
    "midnight": "అర్ధరాత్రి",
    "forest": "అడవి",
    "ocean": "మహాసముద్రం",
    "rose": "గులాబీ",
    "lavender": "లావెండర్",
    "mint": "పుదీనా",
    "sand": "ఇసుక",
    "charcoal": "బొగ్గు",
    "sky": "ఆకాశం",
    "coffee": "కాఫీ",
    "grape": "ద్రాక్ష",
    "sunset": "సూర్యాస్తమయం",
    "ice": "మంచు",
    "ink": "సిరా"
  },
  "mr": {
    "paper": "कागद",
    "midnight": "मध्यरात्री",
    "forest": "जंगल",
    "ocean": "महासागर",
    "rose": "गुलाब",
    "lavender": "लॅव्हेंडर",
    "mint": "मिंट",
    "sand": "वाळू",
    "charcoal": "कोळसा",
    "sky": "आकाश",
    "coffee": "कॉफी",
    "grape": "द्राक्ष",
    "sunset": "सूर्यास्त",
    "ice": "बर्फ",
    "ink": "शाई"
  },
  "gu": {
    "paper": "કાગળ",
    "midnight": "મધરાત",
    "forest": "વન",
    "ocean": "મહાસાગર",
    "rose": "ગુલાબ",
    "lavender": "લવંડર",
    "mint": "ટંકશાળ",
    "sand": "રેતી",
    "charcoal": "ચારકોલ",
    "sky": "આકાશ",
    "coffee": "કોફી",
    "grape": "દ્રાક્ષ",
    "sunset": "સૂર્યાસ્ત",
    "ice": "બરફ",
    "ink": "શાહી"
  },
  "kn": {
    "paper": "ಪೇಪರ್",
    "midnight": "ಮಧ್ಯರಾತ್ರಿ",
    "forest": "ಅರಣ್ಯ",
    "ocean": "ಸಾಗರ",
    "rose": "ಗುಲಾಬಿ",
    "lavender": "ಲ್ಯಾವೆಂಡರ್",
    "mint": "ಮಿಂಟ್",
    "sand": "ಮರಳು",
    "charcoal": "ಇದ್ದಿಲು",
    "sky": "ಆಕಾಶ",
    "coffee": "ಕಾಫಿ",
    "grape": "ದ್ರಾಕ್ಷಿ",
    "sunset": "ಸೂರ್ಯಾಸ್ತ",
    "ice": "ಐಸ್",
    "ink": "ಶಾಯಿ"
  },
  "ml": {
    "paper": "പേപ്പർ",
    "midnight": "അർദ്ധരാത്രി",
    "forest": "വനം",
    "ocean": "സമുദ്രം",
    "rose": "റോസ്",
    "lavender": "ലാവെൻഡർ",
    "mint": "തുളസി",
    "sand": "മണൽ",
    "charcoal": "കരി",
    "sky": "ആകാശം",
    "coffee": "കാപ്പി",
    "grape": "മുന്തിരി",
    "sunset": "സൂര്യാസ്തമയം",
    "ice": "ഐസ്",
    "ink": "മഷി"
  },
  "ne": {
    "paper": "कागज",
    "midnight": "मध्यरात",
    "forest": "वन",
    "ocean": "महासागर",
    "rose": "गुलाब",
    "lavender": "लैभेन्डर",
    "mint": "पुदिना",
    "sand": "बालुवा",
    "charcoal": "चारकोल",
    "sky": "आकाश",
    "coffee": "कफी",
    "grape": "अंगूर",
    "sunset": "सूर्यास्त",
    "ice": "बरफ",
    "ink": "मसी"
  }
};

export const CLASSIC_TEXT: Record<string, Record<string, string>> = {
  "en": {
    "appSettings": "App settings",
    "settingsHint": "Choose interface language, theme and background. Settings are saved automatically.",
    "background": "App background",
    "addBook": "Add book",
    "editBook": "Edit book",
    "titlePlaceholder": "Enter book title",
    "todayHint": "Go to today",
    "selectedFuture": "You can view this day, but pages can only be entered for today or past days.",
    "backToLibrary": "Back to library",
    "bookCompleted": "Book completed!",
    "quizCreating": "Creating the quiz",
    "quizWait": "Please wait while book information is checked.",
    "quizError": "A reliable quiz could not be created for this title. Check the title and internet connection.",
    "next": "Next question",
    "finish": "Finish test",
    "hint": "Hint",
    "passed": "Test passed!",
    "failed": "Test not passed",
    "result": "Result",
    "retry": "Try again",
    "developerMode": "Developer mode",
    "developerSaved": "Developer mode is saved on this device.",
    "exitDeveloper": "Exit developer mode",
    "developerPassword": "Developer password",
    "unlock": "Unlock",
    "wrongPassword": "Wrong password",
    "notificationsInfo": "Reading reminders are controlled by the device.",
    "openNotificationSettings": "Notification settings",
    "review": "Leave a review",
    "question": "Question",
    "of": "of"
  },
  "ru": {
    "appSettings": "Настройки приложения",
    "settingsHint": "Выберите язык, тему и фон. Настройки сохраняются автоматически.",
    "background": "Фон приложения",
    "addBook": "Добавить книгу",
    "editBook": "Изменить книгу",
    "titlePlaceholder": "Введите название книги",
    "todayHint": "К сегодняшнему дню",
    "selectedFuture": "Этот день можно посмотреть, но вводить страницы можно только за сегодня или прошедшие дни.",
    "backToLibrary": "Назад в библиотеку",
    "bookCompleted": "Книга прочитана!",
    "quizCreating": "Создаётся тест",
    "quizWait": "Подождите, проверяем сведения о книге.",
    "quizError": "Не удалось создать надёжный тест для этой книги. Проверьте название и интернет.",
    "next": "Следующий вопрос",
    "finish": "Завершить тест",
    "hint": "Подсказка",
    "passed": "Тест пройден!",
    "failed": "Тест не пройден",
    "result": "Результат",
    "retry": "Попробовать снова",
    "developerMode": "Режим разработчика",
    "developerSaved": "Режим разработчика сохранён на этом устройстве.",
    "exitDeveloper": "Выйти из режима разработчика",
    "developerPassword": "Пароль разработчика",
    "unlock": "Открыть",
    "wrongPassword": "Неверный пароль",
    "notificationsInfo": "Напоминания о чтении управляются настройками устройства.",
    "openNotificationSettings": "Настройки уведомлений",
    "review": "Оставить отзыв",
    "question": "Вопрос",
    "of": "из"
  },
  "es": {
    "appSettings": "Configuración de la aplicación",
    "settingsHint": "Elija el idioma, el tema y el fondo de la interfaz. La configuración se guarda automáticamente.",
    "background": "Fondo de la aplicación",
    "addBook": "Añadir libro",
    "editBook": "Editar libro",
    "titlePlaceholder": "Introduzca el título del libro",
    "todayHint": "ir a hoy",
    "selectedFuture": "Puede ver este día, pero solo se pueden ingresar páginas de hoy o de días anteriores.",
    "backToLibrary": "volver a la biblioteca",
    "bookCompleted": "¡Libro completado!",
    "quizCreating": "Creando el cuestionario",
    "quizWait": "Espere mientras se verifica la información del libro.",
    "quizError": "No se pudo crear una prueba confiable para este título. Consulta el título y la conexión a Internet.",
    "next": "Siguiente pregunta",
    "finish": "Terminar la prueba",
    "hint": "pista",
    "passed": "¡Prueba superada!",
    "failed": "Prueba no superada",
    "result": "Resultado",
    "retry": "Inténtalo de nuevo",
    "developerMode": "Modo desarrollador",
    "developerSaved": "El modo de desarrollador se guarda en este dispositivo.",
    "exitDeveloper": "Salir del modo desarrollador",
    "developerPassword": "Contraseña de desarrollador",
    "unlock": "Desbloquear",
    "wrongPassword": "Contraseña incorrecta",
    "notificationsInfo": "Los recordatorios de lectura están controlados por el dispositivo.",
    "openNotificationSettings": "Configuración de notificaciones",
    "review": "Deja una reseña",
    "question": "Pregunta",
    "of": "de"
  },
  "zh": {
    "appSettings": "应用程序设置",
    "settingsHint": "选择界面语言、主题和背景。设置会自动保存。",
    "background": "应用背景",
    "addBook": "添加图书",
    "editBook": "编辑书籍",
    "titlePlaceholder": "输入书名",
    "todayHint": "转到今天",
    "selectedFuture": "您可以查看这一天，但只能输入今天或过去几天的页面。",
    "backToLibrary": "返回图书馆",
    "bookCompleted": "本书完成！",
    "quizCreating": "创建测验",
    "quizWait": "正在检查图书信息，请稍候。",
    "quizError": "无法为此标题创建可靠的测验。检查标题和互联网连接。",
    "next": "下一个问题",
    "finish": "完成测试",
    "hint": "提示",
    "passed": "测试通过！",
    "failed": "测试未通过",
    "result": "结果",
    "retry": "再试一次",
    "developerMode": "开发者模式",
    "developerSaved": "开发者模式保存在此设备上。",
    "exitDeveloper": "退出开发者模式",
    "developerPassword": "开发者密码",
    "unlock": "解锁",
    "wrongPassword": "密码错误",
    "notificationsInfo": "阅读提醒由设备控制。",
    "openNotificationSettings": "通知设置",
    "review": "发表评论",
    "question": "问题",
    "of": "的"
  },
  "hi": {
    "appSettings": "ऐप सेटिंग",
    "settingsHint": "इंटरफ़ेस भाषा, थीम और पृष्ठभूमि चुनें. सेटिंग्स स्वचालित रूप से सहेजी जाती हैं.",
    "background": "ऐप पृष्ठभूमि",
    "addBook": "पुस्तक जोड़ें",
    "editBook": "पुस्तक संपादित करें",
    "titlePlaceholder": "पुस्तक का शीर्षक दर्ज करें",
    "todayHint": "आज ही जाएं",
    "selectedFuture": "आप इस दिन को देख सकते हैं, लेकिन पृष्ठ केवल आज या पिछले दिनों के लिए ही दर्ज किए जा सकते हैं।",
    "backToLibrary": "लाइब्रेरी में वापस जाएँ",
    "bookCompleted": "किताब पूरी!",
    "quizCreating": "प्रश्नोत्तरी बनाना",
    "quizWait": "कृपया पुस्तक की जानकारी जाँचने तक प्रतीक्षा करें।",
    "quizError": "इस शीर्षक के लिए कोई विश्वसनीय प्रश्नोत्तरी नहीं बनाई जा सकी. शीर्षक और इंटरनेट कनेक्शन की जाँच करें.",
    "next": "अगला प्रश्न",
    "finish": "परीक्षण समाप्त करें",
    "hint": "संकेत",
    "passed": "परीक्षा उत्तीर्ण!",
    "failed": "टेस्ट पास नहीं हुआ",
    "result": "नतीजा",
    "retry": "पुनः प्रयास करें",
    "developerMode": "डेवलपर मोड",
    "developerSaved": "इस डिवाइस पर डेवलपर मोड सहेजा गया है.",
    "exitDeveloper": "डेवलपर मोड से बाहर निकलें",
    "developerPassword": "डेवलपर पासवर्ड",
    "unlock": "अनलॉक",
    "wrongPassword": "ग़लत पासवर्ड",
    "notificationsInfo": "रीडिंग रिमाइंडर डिवाइस द्वारा नियंत्रित होते हैं।",
    "openNotificationSettings": "अधिसूचना सेटिंग्स",
    "review": "एक समीक्षा छोड़ें",
    "question": "प्रश्न",
    "of": "का"
  },
  "ar": {
    "appSettings": "إعدادات التطبيق",
    "settingsHint": "اختر لغة الواجهة والموضوع والخلفية. يتم حفظ الإعدادات تلقائيًا.",
    "background": "خلفية التطبيق",
    "addBook": "إضافة كتاب",
    "editBook": "تحرير الكتاب",
    "titlePlaceholder": "أدخل عنوان الكتاب",
    "todayHint": "اذهب الى اليوم",
    "selectedFuture": "يمكنك عرض هذا اليوم، ولكن لا يمكن إدخال الصفحات إلا لليوم أو الأيام الماضية.",
    "backToLibrary": "العودة إلى المكتبة",
    "bookCompleted": "اكتمل الكتاب!",
    "quizCreating": "إنشاء الاختبار",
    "quizWait": "يرجى الانتظار حتى يتم التحقق من معلومات الكتاب.",
    "quizError": "لا يمكن إنشاء اختبار موثوق لهذا العنوان. تحقق من العنوان والاتصال بالإنترنت.",
    "next": "السؤال التالي",
    "finish": "إنهاء الاختبار",
    "hint": "تلميح",
    "passed": "نجح الاختبار!",
    "failed": "لم يتم اجتياز الاختبار",
    "result": "النتيجة",
    "retry": "حاول مرة أخرى",
    "developerMode": "وضع المطور",
    "developerSaved": "يتم حفظ وضع المطور على هذا الجهاز.",
    "exitDeveloper": "الخروج من وضع المطور",
    "developerPassword": "كلمة مرور المطور",
    "unlock": "فتح",
    "wrongPassword": "كلمة مرور خاطئة",
    "notificationsInfo": "يتم التحكم في تذكيرات القراءة بواسطة الجهاز.",
    "openNotificationSettings": "إعدادات الإخطار",
    "review": "ترك التعليق",
    "question": "سؤال",
    "of": "من"
  },
  "pt": {
    "appSettings": "Configurações do aplicativo",
    "settingsHint": "Escolha o idioma da interface, tema e plano de fundo. As configurações são salvas automaticamente.",
    "background": "Plano de fundo do aplicativo",
    "addBook": "Adicionar livro",
    "editBook": "Editar livro",
    "titlePlaceholder": "Digite o título do livro",
    "todayHint": "Vá para hoje",
    "selectedFuture": "Você pode visualizar este dia, mas as páginas só podem ser acessadas para hoje ou dias anteriores.",
    "backToLibrary": "De volta à biblioteca",
    "bookCompleted": "Livro concluído!",
    "quizCreating": "Criando o questionário",
    "quizWait": "Aguarde enquanto as informações do livro são verificadas.",
    "quizError": "Não foi possível criar um questionário confiável para este título. Verifique o título e a conexão com a internet.",
    "next": "Próxima pergunta",
    "finish": "Concluir teste",
    "hint": "Dica",
    "passed": "Teste aprovado!",
    "failed": "Teste não aprovado",
    "result": "Resultado",
    "retry": "Tente novamente",
    "developerMode": "Modo de desenvolvedor",
    "developerSaved": "O modo de desenvolvedor está salvo neste dispositivo.",
    "exitDeveloper": "Sair do modo de desenvolvedor",
    "developerPassword": "Senha do desenvolvedor",
    "unlock": "Desbloquear",
    "wrongPassword": "Senha errada",
    "notificationsInfo": "Os lembretes de leitura são controlados pelo dispositivo.",
    "openNotificationSettings": "Configurações de notificação",
    "review": "Deixe um comentário",
    "question": "Pergunta",
    "of": "de"
  },
  "bn": {
    "appSettings": "অ্যাপ সেটিংস",
    "settingsHint": "ইন্টারফেস ভাষা, থিম এবং পটভূমি চয়ন করুন. সেটিংস স্বয়ংক্রিয়ভাবে সংরক্ষিত হয়.",
    "background": "অ্যাপের পটভূমি",
    "addBook": "বই যোগ করুন",
    "editBook": "বই সম্পাদনা করুন",
    "titlePlaceholder": "বইয়ের শিরোনাম লিখুন",
    "todayHint": "আজ যাও",
    "selectedFuture": "আপনি এই দিন দেখতে পারেন, কিন্তু পৃষ্ঠাগুলি শুধুমাত্র আজকের বা বিগত দিনের জন্য প্রবেশ করা যেতে পারে।",
    "backToLibrary": "লাইব্রেরিতে ফিরে যান",
    "bookCompleted": "বই সম্পূর্ণ!",
    "quizCreating": "কুইজ তৈরি করা হচ্ছে",
    "quizWait": "বই তথ্য চেক করা হয় যখন অপেক্ষা করুন.",
    "quizError": "এই শিরোনামের জন্য একটি নির্ভরযোগ্য ক্যুইজ তৈরি করা যায়নি। শিরোনাম এবং ইন্টারনেট সংযোগ পরীক্ষা করুন.",
    "next": "পরবর্তী প্রশ্ন",
    "finish": "পরীক্ষা শেষ করুন",
    "hint": "ইঙ্গিত",
    "passed": "পরীক্ষায় উত্তীর্ণ!",
    "failed": "পরীক্ষায় উত্তীর্ণ হয়নি",
    "result": "ফলাফল",
    "retry": "আবার চেষ্টা করুন",
    "developerMode": "বিকাশকারী মোড",
    "developerSaved": "ডেভেলপার মোড এই ডিভাইসে সংরক্ষিত আছে।",
    "exitDeveloper": "বিকাশকারী মোড থেকে প্রস্থান করুন",
    "developerPassword": "বিকাশকারীর পাসওয়ার্ড",
    "unlock": "আনলক করুন",
    "wrongPassword": "ভুল পাসওয়ার্ড",
    "notificationsInfo": "রিডিং রিমাইন্ডার ডিভাইস দ্বারা নিয়ন্ত্রিত হয়।",
    "openNotificationSettings": "বিজ্ঞপ্তি সেটিংস",
    "review": "একটি পর্যালোচনা ছেড়ে",
    "question": "প্রশ্ন",
    "of": "এর"
  },
  "fr": {
    "appSettings": "Paramètres de l'application",
    "settingsHint": "Choisissez la langue, le thème et l'arrière-plan de l'interface. Les paramètres sont enregistrés automatiquement.",
    "background": "Arrière-plan de l'application",
    "addBook": "Ajouter un livre",
    "editBook": "Modifier le livre",
    "titlePlaceholder": "Entrez le titre du livre",
    "todayHint": "Allez à aujourd'hui",
    "selectedFuture": "Vous pouvez afficher ce jour, mais les pages ne peuvent être saisies que pour aujourd'hui ou les jours passés.",
    "backToLibrary": "Retour à la bibliothèque",
    "bookCompleted": "Livre terminé !",
    "quizCreating": "Création du quiz",
    "quizWait": "Veuillez patienter pendant que les informations sur le livre sont vérifiées.",
    "quizError": "Un quiz fiable n'a pas pu être créé pour ce titre. Vérifiez le titre et la connexion Internet.",
    "next": "Question suivante",
    "finish": "Terminer l'essai",
    "hint": "Indice",
    "passed": "Test réussi !",
    "failed": "Test non réussi",
    "result": "Résultat",
    "retry": "Réessayez",
    "developerMode": "Mode développeur",
    "developerSaved": "Le mode développeur est enregistré sur cet appareil.",
    "exitDeveloper": "Quitter le mode développeur",
    "developerPassword": "Mot de passe développeur",
    "unlock": "Déverrouiller",
    "wrongPassword": "Mauvais mot de passe",
    "notificationsInfo": "Les rappels de lecture sont contrôlés par l'appareil.",
    "openNotificationSettings": "Paramètres de notification",
    "review": "Laisser un avis",
    "question": "Question",
    "of": "de"
  },
  "de": {
    "appSettings": "App-Einstellungen",
    "settingsHint": "Wählen Sie die Sprache, das Thema und den Hintergrund der Benutzeroberfläche. Einstellungen werden automatisch gespeichert.",
    "background": "App-Hintergrund",
    "addBook": "Buch hinzufügen",
    "editBook": "Buch bearbeiten",
    "titlePlaceholder": "Buchtitel eingeben",
    "todayHint": "Gehen Sie zu heute",
    "selectedFuture": "Sie können diesen Tag anzeigen, aber Seiten können nur für heute oder vergangene Tage eingegeben werden.",
    "backToLibrary": "Zurück zur Bibliothek",
    "bookCompleted": "Buch abgeschlossen!",
    "quizCreating": "Erstellen des Quiz",
    "quizWait": "Bitte warten Sie, während die Buchinformationen überprüft werden.",
    "quizError": "Für diesen Titel konnte kein zuverlässiges Quiz erstellt werden. Überprüfen Sie den Titel und die Internetverbindung.",
    "next": "Nächste Frage",
    "finish": "Test beenden",
    "hint": "Hinweis",
    "passed": "Test bestanden!",
    "failed": "Prüfung nicht bestanden",
    "result": "Ergebnis",
    "retry": "Versuchen Sie es erneut",
    "developerMode": "Entwicklermodus",
    "developerSaved": "Der Entwicklermodus ist auf diesem Gerät gespeichert.",
    "exitDeveloper": "Beenden Sie den Entwicklermodus",
    "developerPassword": "Entwicklerpasswort",
    "unlock": "Entsperren",
    "wrongPassword": "Falsches Passwort",
    "notificationsInfo": "Leseerinnerungen werden vom Gerät gesteuert.",
    "openNotificationSettings": "Benachrichtigungseinstellungen",
    "review": "Hinterlassen Sie eine Bewertung",
    "question": "Frage",
    "of": "von"
  },
  "ja": {
    "appSettings": "アプリの設定",
    "settingsHint": "インターフェース言語、テーマ、背景を選択します。設定は自動的に保存されます。",
    "background": "アプリの背景",
    "addBook": "本を追加",
    "editBook": "本を編集する",
    "titlePlaceholder": "本のタイトルを入力してください",
    "todayHint": "今日に行く",
    "selectedFuture": "この日を表示することはできますが、ページに入ることができるのは今日または過去の日のみです。",
    "backToLibrary": "ライブラリに戻る",
    "bookCompleted": "本が完成しました！",
    "quizCreating": "クイズの作成",
    "quizWait": "書籍情報を確認中ですのでお待ちください。",
    "quizError": "このタイトルでは信頼できるクイズを作成できませんでした。タイトルとインターネット接続を確認してください。",
    "next": "次の質問",
    "finish": "テストを終了する",
    "hint": "ヒント",
    "passed": "テストに合格しました！",
    "failed": "テストに合格しませんでした",
    "result": "結果",
    "retry": "もう一度試してください",
    "developerMode": "開発者モード",
    "developerSaved": "開発者モードはこのデバイスに保存されます。",
    "exitDeveloper": "開発者モードを終了する",
    "developerPassword": "開発者パスワード",
    "unlock": "ロックを解除する",
    "wrongPassword": "パスワードが間違っています",
    "notificationsInfo": "読書リマインダーはデバイスによって制御されます。",
    "openNotificationSettings": "通知設定",
    "review": "レビューを残す",
    "question": "質問",
    "of": "の"
  },
  "ko": {
    "appSettings": "앱 설정",
    "settingsHint": "인터페이스 언어, 테마, 배경을 선택하세요. 설정은 자동으로 저장됩니다.",
    "background": "앱 배경",
    "addBook": "도서 추가",
    "editBook": "책 편집",
    "titlePlaceholder": "책 제목을 입력하세요",
    "todayHint": "오늘로 이동",
    "selectedFuture": "해당 날짜를 볼 수 있지만 페이지는 오늘 또는 지난 날짜에 대해서만 입력할 수 있습니다.",
    "backToLibrary": "도서관으로 돌아가기",
    "bookCompleted": "책 완성!",
    "quizCreating": "퀴즈 만들기",
    "quizWait": "도서 정보를 확인하는 동안 잠시 기다려 주세요.",
    "quizError": "이 제목에 대한 신뢰할 수 있는 퀴즈를 만들 수 없습니다. 제목과 인터넷 연결을 확인하세요.",
    "next": "다음 질문",
    "finish": "테스트 완료",
    "hint": "힌트",
    "passed": "테스트 통과!",
    "failed": "테스트가 통과되지 않았습니다.",
    "result": "결과",
    "retry": "다시 시도하세요",
    "developerMode": "개발자 모드",
    "developerSaved": "개발자 모드가 이 기기에 저장되었습니다.",
    "exitDeveloper": "개발자 모드 종료",
    "developerPassword": "개발자 비밀번호",
    "unlock": "잠금 해제",
    "wrongPassword": "잘못된 비밀번호",
    "notificationsInfo": "읽기 알림은 장치에 의해 제어됩니다.",
    "openNotificationSettings": "알림 설정",
    "review": "리뷰를 남겨주세요",
    "question": "질문",
    "of": "의"
  },
  "tr": {
    "appSettings": "Uygulama ayarları",
    "settingsHint": "Arayüz dilini, temayı ve arka planı seçin. Ayarlar otomatik olarak kaydedilir.",
    "background": "Uygulama arka planı",
    "addBook": "Kitap ekle",
    "editBook": "Kitabı düzenle",
    "titlePlaceholder": "Kitap başlığını girin",
    "todayHint": "Bugüne git",
    "selectedFuture": "Bu günü görüntüleyebilirsiniz ancak sayfalara yalnızca bugüne veya geçmiş günlere ait girilebilir.",
    "backToLibrary": "Kütüphaneye geri dön",
    "bookCompleted": "Kitap tamamlandı!",
    "quizCreating": "Testi oluşturma",
    "quizWait": "Kitap bilgileri kontrol edilirken lütfen bekleyin.",
    "quizError": "Bu başlık için güvenilir bir test oluşturulamadı. Başlığı ve internet bağlantısını kontrol edin.",
    "next": "Sonraki soru",
    "finish": "Testi bitir",
    "hint": "İpucu",
    "passed": "Test geçti!",
    "failed": "Test geçilmedi",
    "result": "Sonuç",
    "retry": "Tekrar dene",
    "developerMode": "Geliştirici modu",
    "developerSaved": "Geliştirici modu bu cihaza kaydedildi.",
    "exitDeveloper": "Geliştirici modundan çık",
    "developerPassword": "Geliştirici şifresi",
    "unlock": "Kilidi aç",
    "wrongPassword": "Yanlış şifre",
    "notificationsInfo": "Okuma hatırlatıcıları cihaz tarafından kontrol edilir.",
    "openNotificationSettings": "Bildirim ayarları",
    "review": "Yorum bırakın",
    "question": "Soru",
    "of": "arasında"
  },
  "it": {
    "appSettings": "Impostazioni dell'app",
    "settingsHint": "Scegli la lingua dell'interfaccia, il tema e lo sfondo. Le impostazioni vengono salvate automaticamente.",
    "background": "Sfondo dell'app",
    "addBook": "Aggiungi libro",
    "editBook": "Modifica libro",
    "titlePlaceholder": "Inserisci il titolo del libro",
    "todayHint": "Vai a oggi",
    "selectedFuture": "È possibile visualizzare questo giorno, ma è possibile inserire solo le pagine di oggi o dei giorni precedenti.",
    "backToLibrary": "Ritorno in biblioteca",
    "bookCompleted": "Libro completato!",
    "quizCreating": "Creazione del quiz",
    "quizWait": "Attendi mentre vengono controllate le informazioni sul libro.",
    "quizError": "Impossibile creare un quiz affidabile per questo titolo. Controlla il titolo e la connessione internet.",
    "next": "Prossima domanda",
    "finish": "Termina la prova",
    "hint": "Suggerimento",
    "passed": "Prova superata!",
    "failed": "Prova non superata",
    "result": "Risultato",
    "retry": "Riprova",
    "developerMode": "Modalità sviluppatore",
    "developerSaved": "La modalità sviluppatore è salvata su questo dispositivo.",
    "exitDeveloper": "Esci dalla modalità sviluppatore",
    "developerPassword": "Password dello sviluppatore",
    "unlock": "Sblocca",
    "wrongPassword": "Password errata",
    "notificationsInfo": "I promemoria di lettura sono controllati dal dispositivo.",
    "openNotificationSettings": "Impostazioni di notifica",
    "review": "Lascia una recensione",
    "question": "Domanda",
    "of": "di"
  },
  "pl": {
    "appSettings": "Ustawienia aplikacji",
    "settingsHint": "Wybierz język interfejsu, motyw i tło. Ustawienia są zapisywane automatycznie.",
    "background": "Tło aplikacji",
    "addBook": "Dodaj książkę",
    "editBook": "Edytuj książkę",
    "titlePlaceholder": "Wpisz tytuł książki",
    "todayHint": "Przejdź do dzisiaj",
    "selectedFuture": "Możesz wyświetlić ten dzień, ale strony można wprowadzać tylko dla dnia dzisiejszego lub dni przeszłych.",
    "backToLibrary": "Powrót do biblioteki",
    "bookCompleted": "Książka ukończona!",
    "quizCreating": "Tworzenie quizu",
    "quizWait": "Proszę czekać, trwa sprawdzanie informacji o książce.",
    "quizError": "Nie można było stworzyć wiarygodnego quizu dla tego tytułu. Sprawdź tytuł i połączenie internetowe.",
    "next": "Następne pytanie",
    "finish": "Zakończ test",
    "hint": "Wskazówka",
    "passed": "Test zaliczony!",
    "failed": "Test nie zaliczony",
    "result": "Wynik",
    "retry": "Spróbuj ponownie",
    "developerMode": "Tryb programisty",
    "developerSaved": "Tryb programisty jest zapisany na tym urządzeniu.",
    "exitDeveloper": "Wyjdź z trybu programisty",
    "developerPassword": "Hasło programisty",
    "unlock": "Odblokuj",
    "wrongPassword": "Błędne hasło",
    "notificationsInfo": "Przypomnienia o czytaniu są kontrolowane przez urządzenie.",
    "openNotificationSettings": "Ustawienia powiadomień",
    "review": "Zostaw recenzję",
    "question": "Pytanie",
    "of": "z"
  },
  "uk": {
    "appSettings": "Налаштування програми",
    "settingsHint": "Choose interface language, theme and background. Settings are saved automatically.",
    "background": "Фон програми",
    "addBook": "Додати книгу",
    "editBook": "Редагувати книгу",
    "titlePlaceholder": "Введіть назву книги",
    "todayHint": "Перейти до сьогоднішнього дня",
    "selectedFuture": "Ви можете переглядати цей день, але сторінки можна вводити лише за сьогодні чи минулі дні.",
    "backToLibrary": "Назад до бібліотеки",
    "bookCompleted": "Книга завершена!",
    "quizCreating": "Створення вікторини",
    "quizWait": "Please wait while book information is checked.",
    "quizError": "Для цієї назви не вдалося створити надійну вікторину. Check the title and internet connection.",
    "next": "Наступне питання",
    "finish": "Закінчити тест",
    "hint": "Підказка",
    "passed": "Тест пройдено!",
    "failed": "Тест не пройдено",
    "result": "Результат",
    "retry": "Спробуйте знову",
    "developerMode": "Режим розробника",
    "developerSaved": "Developer mode is saved on this device.",
    "exitDeveloper": "Вийти з режиму розробника",
    "developerPassword": "Пароль розробника",
    "unlock": "Розблокувати",
    "wrongPassword": "Неправильний пароль",
    "notificationsInfo": "Reading reminders are controlled by the device.",
    "openNotificationSettings": "Налаштування сповіщень",
    "review": "Залиште відгук",
    "question": "Питання",
    "of": "з"
  },
  "nl": {
    "appSettings": "App-instellingen",
    "settingsHint": "Kies interfacetaal, thema en achtergrond. Instellingen worden automatisch opgeslagen.",
    "background": "App-achtergrond",
    "addBook": "Boek toevoegen",
    "editBook": "Boek bewerken",
    "titlePlaceholder": "Voer de boektitel in",
    "todayHint": "Ga naar vandaag",
    "selectedFuture": "U kunt deze dag bekijken, maar pagina's kunnen alleen voor vandaag of afgelopen dagen worden geopend.",
    "backToLibrary": "Terug naar bibliotheek",
    "bookCompleted": "Boek voltooid!",
    "quizCreating": "Het maken van de quiz",
    "quizWait": "Een ogenblik geduld terwijl de boekinformatie wordt gecontroleerd.",
    "quizError": "Voor deze titel kon geen betrouwbare quiz worden gemaakt. Controleer de titel en internetverbinding.",
    "next": "Volgende vraag",
    "finish": "Beëindig de proef",
    "hint": "Tip",
    "passed": "Test geslaagd!",
    "failed": "Test niet geslaagd",
    "result": "Resultaat",
    "retry": "Probeer het opnieuw",
    "developerMode": "Ontwikkelaarsmodus",
    "developerSaved": "De ontwikkelaarsmodus is op dit apparaat opgeslagen.",
    "exitDeveloper": "Verlaat de ontwikkelaarsmodus",
    "developerPassword": "Ontwikkelaarswachtwoord",
    "unlock": "Ontgrendelen",
    "wrongPassword": "Verkeerd wachtwoord",
    "notificationsInfo": "Leesherinneringen worden beheerd door het apparaat.",
    "openNotificationSettings": "Meldingsinstellingen",
    "review": "Laat een recensie achter",
    "question": "Vraag",
    "of": "van"
  },
  "id": {
    "appSettings": "Pengaturan aplikasi",
    "settingsHint": "Pilih bahasa antarmuka, tema dan latar belakang. Pengaturan disimpan secara otomatis.",
    "background": "Latar belakang aplikasi",
    "addBook": "Tambahkan buku",
    "editBook": "Sunting buku",
    "titlePlaceholder": "Masukkan judul buku",
    "todayHint": "Pergi ke hari ini",
    "selectedFuture": "Anda dapat melihat hari ini, namun halaman hanya dapat dimasuki untuk hari ini atau beberapa hari yang lalu.",
    "backToLibrary": "Kembali ke perpustakaan",
    "bookCompleted": "Buku selesai!",
    "quizCreating": "Membuat kuis",
    "quizWait": "Harap tunggu sementara informasi buku diperiksa.",
    "quizError": "Kuis yang andal tidak dapat dibuat untuk judul ini. Periksa judul dan koneksi internet.",
    "next": "Pertanyaan berikutnya",
    "finish": "Selesaikan tes",
    "hint": "Petunjuk",
    "passed": "Tes lulus!",
    "failed": "Tes tidak lulus",
    "result": "Hasil",
    "retry": "Coba lagi",
    "developerMode": "Mode pengembang",
    "developerSaved": "Mode pengembang disimpan di perangkat ini.",
    "exitDeveloper": "Keluar dari mode pengembang",
    "developerPassword": "Kata sandi pengembang",
    "unlock": "Buka kunci",
    "wrongPassword": "Kata sandi salah",
    "notificationsInfo": "Pengingat membaca dikendalikan oleh perangkat.",
    "openNotificationSettings": "Pengaturan notifikasi",
    "review": "Tinggalkan ulasan",
    "question": "Pertanyaan",
    "of": "dari"
  },
  "vi": {
    "appSettings": "Cài đặt ứng dụng",
    "settingsHint": "Chọn ngôn ngữ giao diện, chủ đề và nền. Cài đặt được lưu tự động.",
    "background": "Nền ứng dụng",
    "addBook": "Thêm sách",
    "editBook": "Chỉnh sửa sách",
    "titlePlaceholder": "Nhập tên sách",
    "todayHint": "Tới ngày hôm nay",
    "selectedFuture": "Bạn có thể xem ngày này, nhưng các trang chỉ có thể được nhập vào ngày hôm nay hoặc những ngày trước đó.",
    "backToLibrary": "Quay lại thư viện",
    "bookCompleted": "Sách đã hoàn thành!",
    "quizCreating": "Tạo bài kiểm tra",
    "quizWait": "Vui lòng đợi trong khi thông tin sách được kiểm tra.",
    "quizError": "Không thể tạo một bài kiểm tra đáng tin cậy cho tựa đề này. Kiểm tra tiêu đề và kết nối internet.",
    "next": "Câu hỏi tiếp theo",
    "finish": "Kết thúc bài kiểm tra",
    "hint": "gợi ý",
    "passed": "Đã vượt qua bài kiểm tra!",
    "failed": "Bài kiểm tra không đạt",
    "result": "kết quả",
    "retry": "Thử lại",
    "developerMode": "Chế độ nhà phát triển",
    "developerSaved": "Chế độ nhà phát triển được lưu trên thiết bị này.",
    "exitDeveloper": "Thoát chế độ nhà phát triển",
    "developerPassword": "Mật khẩu nhà phát triển",
    "unlock": "Mở khóa",
    "wrongPassword": "Mật khẩu sai",
    "notificationsInfo": "Lời nhắc đọc được điều khiển bởi thiết bị.",
    "openNotificationSettings": "Cài đặt thông báo",
    "review": "Để lại đánh giá",
    "question": "Câu hỏi",
    "of": "của"
  },
  "th": {
    "appSettings": "การตั้งค่าแอพ",
    "settingsHint": "เลือกภาษา ธีม และพื้นหลังของอินเทอร์เฟซ การตั้งค่าจะถูกบันทึกโดยอัตโนมัติ",
    "background": "พื้นหลังของแอป",
    "addBook": "เพิ่มหนังสือ",
    "editBook": "แก้ไขหนังสือ",
    "titlePlaceholder": "ป้อนชื่อหนังสือ",
    "todayHint": "ไปวันนี้",
    "selectedFuture": "คุณสามารถดูวันนี้ได้ แต่สามารถป้อนหน้าได้เฉพาะวันนี้หรือวันที่ผ่านมาเท่านั้น",
    "backToLibrary": "กลับไปที่ห้องสมุด",
    "bookCompleted": "หนังสือจบแล้ว!",
    "quizCreating": "การสร้างแบบทดสอบ",
    "quizWait": "กรุณารอสักครู่ในขณะที่ตรวจสอบข้อมูลหนังสือ",
    "quizError": "ไม่สามารถสร้างแบบทดสอบที่เชื่อถือได้สำหรับชื่อเรื่องนี้ ตรวจสอบชื่อเรื่องและการเชื่อมต่ออินเทอร์เน็ต",
    "next": "คำถามต่อไป",
    "finish": "เสร็จสิ้นการทดสอบ",
    "hint": "คำแนะนำ",
    "passed": "ผ่านการทดสอบแล้ว!",
    "failed": "การทดสอบไม่ผ่าน",
    "result": "ผลลัพธ์",
    "retry": "ลองอีกครั้ง",
    "developerMode": "โหมดนักพัฒนา",
    "developerSaved": "โหมดนักพัฒนาซอฟต์แวร์ถูกบันทึกไว้ในอุปกรณ์นี้",
    "exitDeveloper": "ออกจากโหมดนักพัฒนาซอฟต์แวร์",
    "developerPassword": "รหัสผ่านสำหรับนักพัฒนา",
    "unlock": "ปลดล็อค",
    "wrongPassword": "รหัสผ่านผิด",
    "notificationsInfo": "การแจ้งเตือนการอ่านจะถูกควบคุมโดยอุปกรณ์",
    "openNotificationSettings": "การตั้งค่าการแจ้งเตือน",
    "review": "แสดงความคิดเห็น",
    "question": "คำถาม",
    "of": "ของ"
  },
  "fa": {
    "appSettings": "تنظیمات برنامه",
    "settingsHint": "زبان رابط، موضوع و پس زمینه را انتخاب کنید. تنظیمات به صورت خودکار ذخیره می شوند.",
    "background": "پس زمینه برنامه",
    "addBook": "کتاب اضافه کنید",
    "editBook": "ویرایش کتاب",
    "titlePlaceholder": "عنوان کتاب را وارد کنید",
    "todayHint": "برو به امروز",
    "selectedFuture": "شما می توانید این روز را مشاهده کنید، اما صفحات فقط برای امروز یا روزهای گذشته قابل ورود هستند.",
    "backToLibrary": "بازگشت به کتابخانه",
    "bookCompleted": "کتاب تکمیل شد!",
    "quizCreating": "ایجاد مسابقه",
    "quizWait": "لطفاً صبر کنید تا اطلاعات کتاب بررسی شود.",
    "quizError": "آزمون قابل اعتمادی برای این عنوان ایجاد نشد. عنوان و اتصال اینترنت را بررسی کنید.",
    "next": "سوال بعدی",
    "finish": "تست را تمام کنید",
    "hint": "اشاره",
    "passed": "آزمون قبول شد!",
    "failed": "آزمون قبول نشد",
    "result": "نتیجه",
    "retry": "دوباره امتحان کنید",
    "developerMode": "حالت توسعه دهنده",
    "developerSaved": "حالت برنامه نویس در این دستگاه ذخیره شده است.",
    "exitDeveloper": "از حالت توسعه دهنده خارج شوید",
    "developerPassword": "رمز عبور توسعه دهنده",
    "unlock": "باز کردن قفل",
    "wrongPassword": "رمز عبور اشتباه",
    "notificationsInfo": "یادآوری خواندن توسط دستگاه کنترل می شود.",
    "openNotificationSettings": "تنظیمات اعلان",
    "review": "نظر بدهید",
    "question": "سوال",
    "of": "از"
  },
  "ur": {
    "appSettings": "ایپ کی ترتیبات",
    "settingsHint": "انٹرفیس کی زبان، تھیم اور پس منظر کا انتخاب کریں۔ ترتیبات خود بخود محفوظ ہوجاتی ہیں۔",
    "background": "ایپ کا پس منظر",
    "addBook": "کتاب شامل کریں۔",
    "editBook": "کتاب میں ترمیم کریں۔",
    "titlePlaceholder": "کتاب کا عنوان درج کریں۔",
    "todayHint": "آج کے پاس جائیں۔",
    "selectedFuture": "آپ اس دن کو دیکھ سکتے ہیں، لیکن صفحات صرف آج یا گزشتہ دنوں کے لیے درج کیے جا سکتے ہیں۔",
    "backToLibrary": "لائبریری پر واپس جائیں۔",
    "bookCompleted": "کتاب مکمل!",
    "quizCreating": "کوئز بنانا",
    "quizWait": "براہ کرم کتاب کی معلومات چیک ہونے تک انتظار کریں۔",
    "quizError": "اس عنوان کے لیے قابل اعتماد کوئز نہیں بنایا جا سکا۔ عنوان اور انٹرنیٹ کنیکشن چیک کریں۔",
    "next": "اگلا سوال",
    "finish": "ٹیسٹ ختم کریں۔",
    "hint": "اشارہ",
    "passed": "امتحان پاس!",
    "failed": "امتحان پاس نہیں ہوا۔",
    "result": "نتیجہ",
    "retry": "دوبارہ کوشش کریں۔",
    "developerMode": "ڈویلپر موڈ",
    "developerSaved": "ڈیولپر موڈ اس ڈیوائس پر محفوظ ہے۔",
    "exitDeveloper": "ڈیولپر موڈ سے باہر نکلیں۔",
    "developerPassword": "ڈویلپر پاس ورڈ",
    "unlock": "غیر مقفل کریں۔",
    "wrongPassword": "غلط پاس ورڈ",
    "notificationsInfo": "ریڈنگ ریمائنڈرز ڈیوائس کے ذریعے کنٹرول کیے جاتے ہیں۔",
    "openNotificationSettings": "اطلاع کی ترتیبات",
    "review": "ایک جائزہ چھوڑیں۔",
    "question": "سوال",
    "of": "کی"
  },
  "ms": {
    "appSettings": "Tetapan apl",
    "settingsHint": "Pilih bahasa antara muka, tema dan latar belakang. Tetapan disimpan secara automatik.",
    "background": "Latar belakang apl",
    "addBook": "Tambah buku",
    "editBook": "Edit buku",
    "titlePlaceholder": "Masukkan tajuk buku",
    "todayHint": "Pergi ke hari ini",
    "selectedFuture": "Anda boleh melihat hari ini, tetapi halaman hanya boleh dimasukkan untuk hari ini atau hari lalu.",
    "backToLibrary": "Kembali ke perpustakaan",
    "bookCompleted": "Buku siap!",
    "quizCreating": "Mencipta kuiz",
    "quizWait": "Sila tunggu sementara maklumat buku disemak.",
    "quizError": "Kuiz yang boleh dipercayai tidak dapat dibuat untuk tajuk ini. Semak tajuk dan sambungan internet.",
    "next": "Soalan seterusnya",
    "finish": "Selesai ujian",
    "hint": "Petunjuk",
    "passed": "Ujian lulus!",
    "failed": "Ujian tidak lulus",
    "result": "Hasilnya",
    "retry": "Cuba lagi",
    "developerMode": "Mod pembangun",
    "developerSaved": "Mod pembangun disimpan pada peranti ini.",
    "exitDeveloper": "Keluar dari mod pembangun",
    "developerPassword": "Kata laluan pembangun",
    "unlock": "Buka kunci",
    "wrongPassword": "Kata laluan salah",
    "notificationsInfo": "Peringatan membaca dikawal oleh peranti.",
    "openNotificationSettings": "Tetapan pemberitahuan",
    "review": "Tinggalkan ulasan",
    "question": "soalan",
    "of": "daripada"
  },
  "fil": {
    "appSettings": "Mga setting ng app",
    "settingsHint": "Pumili ng wika ng interface, tema at background. Awtomatikong nai-save ang mga setting.",
    "background": "Background ng app",
    "addBook": "Magdagdag ng libro",
    "editBook": "I-edit ang aklat",
    "titlePlaceholder": "Ilagay ang pamagat ng aklat",
    "todayHint": "Pumunta sa ngayon",
    "selectedFuture": "Maaari mong tingnan ang araw na ito, ngunit maaari lamang ipasok ang mga pahina para sa ngayon o mga nakaraang araw.",
    "backToLibrary": "Bumalik sa library",
    "bookCompleted": "Nakumpleto ang libro!",
    "quizCreating": "Paggawa ng pagsusulit",
    "quizWait": "Mangyaring maghintay habang sinusuri ang impormasyon ng libro.",
    "quizError": "Ang isang mapagkakatiwalaang pagsusulit ay hindi malikha para sa pamagat na ito. Suriin ang pamagat at koneksyon sa internet.",
    "next": "Sunod sunod na tanong",
    "finish": "Tapusin ang pagsubok",
    "hint": "Pahiwatig",
    "passed": "Natapos ang pagsubok!",
    "failed": "Hindi naipasa ang pagsusulit",
    "result": "Resulta",
    "retry": "Subukan muli",
    "developerMode": "Mode ng developer",
    "developerSaved": "Naka-save ang developer mode sa device na ito.",
    "exitDeveloper": "Lumabas sa developer mode",
    "developerPassword": "Password ng developer",
    "unlock": "I-unlock",
    "wrongPassword": "Maling password",
    "notificationsInfo": "Ang pagbabasa ng mga paalala ay kinokontrol ng device.",
    "openNotificationSettings": "Mga setting ng notification",
    "review": "Mag-iwan ng pagsusuri",
    "question": "Tanong",
    "of": "ng"
  },
  "ro": {
    "appSettings": "Setările aplicației",
    "settingsHint": "Alegeți limba interfeței, tema și fundalul. Setările sunt salvate automat.",
    "background": "Fundalul aplicației",
    "addBook": "Adăugați cartea",
    "editBook": "Editează cartea",
    "titlePlaceholder": "Introduceți titlul cărții",
    "todayHint": "Du-te la azi",
    "selectedFuture": "Puteți vizualiza această zi, dar paginile pot fi introduse numai pentru zilele de astăzi sau trecute.",
    "backToLibrary": "Înapoi la bibliotecă",
    "bookCompleted": "Carte finalizată!",
    "quizCreating": "Crearea testului",
    "quizWait": "Vă rugăm să așteptați până când informațiile cărții sunt verificate.",
    "quizError": "Nu a putut fi creat un test de încredere pentru acest titlu. Verificați titlul și conexiunea la internet.",
    "next": "Următoarea întrebare",
    "finish": "Terminați testul",
    "hint": "Sugestie",
    "passed": "Testul a trecut!",
    "failed": "Testul nu a trecut",
    "result": "Rezultat",
    "retry": "Încercați din nou",
    "developerMode": "Modul dezvoltator",
    "developerSaved": "Modul dezvoltator este salvat pe acest dispozitiv.",
    "exitDeveloper": "Ieși din modul dezvoltator",
    "developerPassword": "Parola de dezvoltator",
    "unlock": "Deblocați",
    "wrongPassword": "Parolă greșită",
    "notificationsInfo": "Mementourile de citire sunt controlate de dispozitiv.",
    "openNotificationSettings": "Setări de notificare",
    "review": "Lasă o recenzie",
    "question": "Întrebare",
    "of": "de"
  },
  "cs": {
    "appSettings": "Nastavení aplikace",
    "settingsHint": "Vyberte jazyk rozhraní, téma a pozadí. Nastavení se uloží automaticky.",
    "background": "Pozadí aplikace",
    "addBook": "Přidat knihu",
    "editBook": "Upravit knihu",
    "titlePlaceholder": "Zadejte název knihy",
    "todayHint": "Přejít na dnešek",
    "selectedFuture": "Tento den můžete zobrazit, ale stránky lze zadat pouze pro dnešní nebo minulé dny.",
    "backToLibrary": "Zpět do knihovny",
    "bookCompleted": "Kniha dokončena!",
    "quizCreating": "Vytvoření kvízu",
    "quizWait": "Počkejte prosím, než se zkontrolují informace o knize.",
    "quizError": "Pro tento titul se nepodařilo vytvořit spolehlivý kvíz. Zkontrolujte název a připojení k internetu.",
    "next": "Další otázka",
    "finish": "Dokončete test",
    "hint": "Nápověda",
    "passed": "Test prošel!",
    "failed": "Test neprošel",
    "result": "Výsledek",
    "retry": "Zkuste to znovu",
    "developerMode": "Vývojářský režim",
    "developerSaved": "V tomto zařízení je uložen vývojářský režim.",
    "exitDeveloper": "Ukončete režim vývojáře",
    "developerPassword": "Heslo vývojáře",
    "unlock": "Odemknout",
    "wrongPassword": "Nesprávné heslo",
    "notificationsInfo": "Připomenutí čtení jsou řízena zařízením.",
    "openNotificationSettings": "Nastavení oznámení",
    "review": "Zanechat recenzi",
    "question": "Otázka",
    "of": "z"
  },
  "el": {
    "appSettings": "Ρυθμίσεις εφαρμογής",
    "settingsHint": "Επιλέξτε γλώσσα διεπαφής, θέμα και φόντο. Οι ρυθμίσεις αποθηκεύονται αυτόματα.",
    "background": "Φόντο εφαρμογής",
    "addBook": "Προσθήκη βιβλίου",
    "editBook": "Επεξεργασία βιβλίου",
    "titlePlaceholder": "Εισαγάγετε τον τίτλο του βιβλίου",
    "todayHint": "Πηγαίνετε στο σήμερα",
    "selectedFuture": "Μπορείτε να δείτε αυτήν την ημέρα, αλλά οι σελίδες μπορούν να εισαχθούν μόνο για σήμερα ή τις προηγούμενες ημέρες.",
    "backToLibrary": "Επιστροφή στη βιβλιοθήκη",
    "bookCompleted": "Το βιβλίο ολοκληρώθηκε!",
    "quizCreating": "Δημιουργία του κουίζ",
    "quizWait": "Περιμένετε μέχρι να ελεγχθούν οι πληροφορίες του βιβλίου.",
    "quizError": "Δεν ήταν δυνατή η δημιουργία αξιόπιστου κουίζ για αυτόν τον τίτλο. Ελέγξτε τον τίτλο και τη σύνδεση στο διαδίκτυο.",
    "next": "Επόμενη ερώτηση",
    "finish": "Τελειώστε τη δοκιμή",
    "hint": "Υπόδειξη",
    "passed": "Το τεστ πέρασε!",
    "failed": "Το τεστ δεν πέρασε",
    "result": "Αποτέλεσμα",
    "retry": "Προσπαθήστε ξανά",
    "developerMode": "Λειτουργία προγραμματιστή",
    "developerSaved": "Η λειτουργία προγραμματιστή είναι αποθηκευμένη σε αυτήν τη συσκευή.",
    "exitDeveloper": "Έξοδος από τη λειτουργία προγραμματιστή",
    "developerPassword": "Κωδικός προγραμματιστή",
    "unlock": "Ξεκλείδωμα",
    "wrongPassword": "Λάθος κωδικός πρόσβασης",
    "notificationsInfo": "Οι υπενθυμίσεις ανάγνωσης ελέγχονται από τη συσκευή.",
    "openNotificationSettings": "Ρυθμίσεις ειδοποιήσεων",
    "review": "Αφήστε μια κριτική",
    "question": "Ερώτηση",
    "of": "του"
  },
  "sv": {
    "appSettings": "Appinställningar",
    "settingsHint": "Välj gränssnittsspråk, tema och bakgrund. Inställningarna sparas automatiskt.",
    "background": "App bakgrund",
    "addBook": "Lägg till bok",
    "editBook": "Redigera bok",
    "titlePlaceholder": "Ange bokens titel",
    "todayHint": "Gå till idag",
    "selectedFuture": "Du kan se den här dagen, men sidor kan endast öppnas för idag eller tidigare dagar.",
    "backToLibrary": "Tillbaka till biblioteket",
    "bookCompleted": "Boken färdig!",
    "quizCreating": "Skapar frågesporten",
    "quizWait": "Vänta medan bokinformationen kontrolleras.",
    "quizError": "En pålitlig frågesport kunde inte skapas för den här titeln. Kontrollera titeln och internetanslutningen.",
    "next": "Nästa fråga",
    "finish": "Avsluta testet",
    "hint": "Tips",
    "passed": "Testet godkänt!",
    "failed": "Testet ej godkänt",
    "result": "Resultat",
    "retry": "Försök igen",
    "developerMode": "Utvecklarläge",
    "developerSaved": "Utvecklarläget är sparat på den här enheten.",
    "exitDeveloper": "Avsluta utvecklarläget",
    "developerPassword": "Utvecklarlösenord",
    "unlock": "Lås upp",
    "wrongPassword": "Fel lösenord",
    "notificationsInfo": "Läspåminnelser styrs av enheten.",
    "openNotificationSettings": "Aviseringsinställningar",
    "review": "Lämna en recension",
    "question": "Fråga",
    "of": "av"
  },
  "hu": {
    "appSettings": "Alkalmazásbeállítások",
    "settingsHint": "Válassza ki a felület nyelvét, témáját és hátterét. A beállítások automatikusan mentésre kerülnek.",
    "background": "App háttér",
    "addBook": "Könyv hozzáadása",
    "editBook": "Könyv szerkesztése",
    "titlePlaceholder": "Írja be a könyv címét",
    "todayHint": "Menj a mai napra",
    "selectedFuture": "Megtekintheti ezt a napot, de oldalakat csak a mai vagy az elmúlt napokra vonatkozóan adhat meg.",
    "backToLibrary": "Vissza a könyvtárba",
    "bookCompleted": "A könyv elkészült!",
    "quizCreating": "A kvíz elkészítése",
    "quizWait": "Kérjük, várjon, amíg a könyv információi ellenőrzésre kerülnek.",
    "quizError": "Ehhez a címhez nem lehetett megbízható kvízt készíteni. Ellenőrizze a címet és az internetkapcsolatot.",
    "next": "Következő kérdés",
    "finish": "Fejezd be a tesztet",
    "hint": "Tipp",
    "passed": "A teszt sikeres!",
    "failed": "Nem sikerült a teszt",
    "result": "Eredmény",
    "retry": "Próbáld újra",
    "developerMode": "Fejlesztői mód",
    "developerSaved": "A fejlesztői mód mentve van ezen az eszközön.",
    "exitDeveloper": "Lépjen ki a fejlesztői módból",
    "developerPassword": "Fejlesztői jelszó",
    "unlock": "Oldja fel",
    "wrongPassword": "Hibás jelszó",
    "notificationsInfo": "Az olvasási emlékeztetőket a készülék vezérli.",
    "openNotificationSettings": "Értesítési beállítások",
    "review": "Hagyjon véleményt",
    "question": "kérdés",
    "of": "a"
  },
  "he": {
    "appSettings": "הגדרות האפליקציה",
    "settingsHint": "בחר שפת ממשק, ערכת נושא ורקע. ההגדרות נשמרות אוטומטית.",
    "background": "רקע אפליקציה",
    "addBook": "הוסף ספר",
    "editBook": "ערוך ספר",
    "titlePlaceholder": "הזן את שם הספר",
    "todayHint": "לך להיום",
    "selectedFuture": "אתה יכול לראות את היום הזה, אבל ניתן להזין דפים רק עבור היום או ימים עברו.",
    "backToLibrary": "חזרה לספרייה",
    "bookCompleted": "הספר הושלם!",
    "quizCreating": "יצירת החידון",
    "quizWait": "אנא המתן בזמן שהמידע על הספר נבדק.",
    "quizError": "לא ניתן היה ליצור חידון אמין עבור הכותר הזה. בדוק את הכותרת והחיבור לאינטרנט.",
    "next": "השאלה הבאה",
    "finish": "סיים את המבחן",
    "hint": "רמז",
    "passed": "המבחן עבר!",
    "failed": "מבחן לא עבר",
    "result": "תוצאה",
    "retry": "נסה שוב",
    "developerMode": "מצב מפתח",
    "developerSaved": "מצב מפתחים נשמר במכשיר זה.",
    "exitDeveloper": "צא ממצב מפתח",
    "developerPassword": "סיסמת מפתח",
    "unlock": "פתח את הנעילה",
    "wrongPassword": "סיסמה שגויה",
    "notificationsInfo": "תזכורות קריאה נשלטות על ידי המכשיר.",
    "openNotificationSettings": "הגדרות התראות",
    "review": "השאירו ביקורת",
    "question": "שאלה",
    "of": "של"
  },
  "da": {
    "appSettings": "App-indstillinger",
    "settingsHint": "Vælg grænsefladesprog, tema og baggrund. Indstillinger gemmes automatisk.",
    "background": "App baggrund",
    "addBook": "Tilføj bog",
    "editBook": "Rediger bog",
    "titlePlaceholder": "Indtast bogtitel",
    "todayHint": "Gå til i dag",
    "selectedFuture": "Du kan se denne dag, men der kan kun indtastes sider for i dag eller tidligere dage.",
    "backToLibrary": "Tilbage til biblioteket",
    "bookCompleted": "Bog færdig!",
    "quizCreating": "Oprettelse af quizzen",
    "quizWait": "Vent venligst, mens bogoplysningerne kontrolleres.",
    "quizError": "En pålidelig quiz kunne ikke oprettes for denne titel. Tjek titlen og internetforbindelsen.",
    "next": "Næste spørgsmål",
    "finish": "Afslut testen",
    "hint": "Tip",
    "passed": "Prøven bestået!",
    "failed": "Prøven ikke bestået",
    "result": "Resultat",
    "retry": "Prøv igen",
    "developerMode": "Udviklertilstand",
    "developerSaved": "Udviklertilstand er gemt på denne enhed.",
    "exitDeveloper": "Afslut udviklertilstand",
    "developerPassword": "Udvikleradgangskode",
    "unlock": "Lås op",
    "wrongPassword": "Forkert adgangskode",
    "notificationsInfo": "Læsepåmindelser styres af enheden.",
    "openNotificationSettings": "Notifikationsindstillinger",
    "review": "Skriv en anmeldelse",
    "question": "Spørgsmål",
    "of": "af"
  },
  "fi": {
    "appSettings": "Sovelluksen asetukset",
    "settingsHint": "Valitse käyttöliittymän kieli, teema ja tausta. Asetukset tallennetaan automaattisesti.",
    "background": "Sovelluksen tausta",
    "addBook": "Lisää kirja",
    "editBook": "Muokkaa kirjaa",
    "titlePlaceholder": "Anna kirjan nimi",
    "todayHint": "Mene tähän päivään",
    "selectedFuture": "Voit tarkastella tätä päivää, mutta sivut voidaan syöttää vain tämän päivän tai menneiden päivien ajalta.",
    "backToLibrary": "Takaisin kirjastoon",
    "bookCompleted": "Kirja valmis!",
    "quizCreating": "Tietokilpailun luominen",
    "quizWait": "Odota, kun kirjan tiedot tarkistetaan.",
    "quizError": "Tälle nimikkeelle ei voitu luoda luotettavaa tietokilpailua. Tarkista otsikko ja internetyhteys.",
    "next": "Seuraava kysymys",
    "finish": "Viimeistele testi",
    "hint": "Vihje",
    "passed": "Testi meni läpi!",
    "failed": "Testi ei läpäissyt",
    "result": "Tulos",
    "retry": "Yritä uudelleen",
    "developerMode": "Kehittäjätila",
    "developerSaved": "Kehittäjätila on tallennettu tälle laitteelle.",
    "exitDeveloper": "Poistu kehittäjätilasta",
    "developerPassword": "Kehittäjän salasana",
    "unlock": "Avaa lukitus",
    "wrongPassword": "Väärä salasana",
    "notificationsInfo": "Laite ohjaa lukumuistutuksia.",
    "openNotificationSettings": "Ilmoitusasetukset",
    "review": "Jätä arvostelu",
    "question": "Kysymys",
    "of": "/"
  },
  "no": {
    "appSettings": "Appinnstillinger",
    "settingsHint": "Velg grensesnittspråk, tema og bakgrunn. Innstillinger lagres automatisk.",
    "background": "App bakgrunn",
    "addBook": "Legg til bok",
    "editBook": "Rediger bok",
    "titlePlaceholder": "Skriv inn boktittel",
    "todayHint": "Gå til i dag",
    "selectedFuture": "Du kan se denne dagen, men sider kan bare legges inn for i dag eller tidligere dager.",
    "backToLibrary": "Tilbake til biblioteket",
    "bookCompleted": "Boken er ferdig!",
    "quizCreating": "Lage quizen",
    "quizWait": "Vennligst vent mens bokinformasjonen er sjekket.",
    "quizError": "En pålitelig quiz kunne ikke opprettes for denne tittelen. Sjekk tittelen og internettforbindelsen.",
    "next": "Neste spørsmål",
    "finish": "Fullfør testen",
    "hint": "Hint",
    "passed": "Testen bestått!",
    "failed": "Prøven ikke bestått",
    "result": "Resultat",
    "retry": "Prøv igjen",
    "developerMode": "Utviklermodus",
    "developerSaved": "Utviklermodus er lagret på denne enheten.",
    "exitDeveloper": "Avslutt utviklermodus",
    "developerPassword": "Utviklerpassord",
    "unlock": "Lås opp",
    "wrongPassword": "Feil passord",
    "notificationsInfo": "Lesepåminnelser styres av enheten.",
    "openNotificationSettings": "Varslingsinnstillinger",
    "review": "Legg igjen en anmeldelse",
    "question": "Spørsmål",
    "of": "av"
  },
  "sk": {
    "appSettings": "Nastavenia aplikácie",
    "settingsHint": "Vyberte jazyk rozhrania, tému a pozadie. Nastavenia sa uložia automaticky.",
    "background": "Pozadie aplikácie",
    "addBook": "Pridať knihu",
    "editBook": "Upraviť knihu",
    "titlePlaceholder": "Zadajte názov knihy",
    "todayHint": "Choďte na dnešok",
    "selectedFuture": "Tento deň môžete zobraziť, ale stránky je možné zadať iba pre dnešný deň alebo pre minulé dni.",
    "backToLibrary": "Späť do knižnice",
    "bookCompleted": "Kniha dokončená!",
    "quizCreating": "Vytvorenie kvízu",
    "quizWait": "Počkajte, kým sa skontrolujú informácie o knihe.",
    "quizError": "Pre tento titul sa nepodarilo vytvoriť spoľahlivý kvíz. Skontrolujte názov a internetové pripojenie.",
    "next": "Ďalšia otázka",
    "finish": "Dokončiť test",
    "hint": "Nápoveda",
    "passed": "Test prešiel!",
    "failed": "Test neprešiel",
    "result": "Výsledok",
    "retry": "Skúste to znova",
    "developerMode": "Vývojársky režim",
    "developerSaved": "Režim vývojára je v tomto zariadení uložený.",
    "exitDeveloper": "Ukončite režim vývojára",
    "developerPassword": "Heslo vývojára",
    "unlock": "Odomknúť",
    "wrongPassword": "Nesprávne heslo",
    "notificationsInfo": "Pripomienky na čítanie sú riadené zariadením.",
    "openNotificationSettings": "Nastavenia upozornení",
    "review": "Napíšte recenziu",
    "question": "Otázka",
    "of": "z"
  },
  "bg": {
    "appSettings": "Настройки на приложението",
    "settingsHint": "Изберете език на интерфейса, тема и фон. Настройките се запазват автоматично.",
    "background": "Фон на приложението",
    "addBook": "Добавете книга",
    "editBook": "Редактиране на книга",
    "titlePlaceholder": "Въведете заглавие на книгата",
    "todayHint": "Отидете до днес",
    "selectedFuture": "Можете да видите този ден, но можете да въвеждате страници само за днес или за минали дни.",
    "backToLibrary": "Обратно към библиотеката",
    "bookCompleted": "Книгата е завършена!",
    "quizCreating": "Създаване на теста",
    "quizWait": "Моля, изчакайте, докато се провери информацията за книгата.",
    "quizError": "За това заглавие не можа да бъде създаден надежден тест. Проверете заглавието и интернет връзката.",
    "next": "Следващ въпрос",
    "finish": "Завършете теста",
    "hint": "Подсказка",
    "passed": "Тестът премина!",
    "failed": "Тестът не е преминат",
    "result": "Резултат",
    "retry": "Опитайте отново",
    "developerMode": "Режим за програмисти",
    "developerSaved": "Режимът за програмисти е запазен на това устройство.",
    "exitDeveloper": "Излезте от режима за програмисти",
    "developerPassword": "Парола на програмист",
    "unlock": "Отключи",
    "wrongPassword": "Грешна парола",
    "notificationsInfo": "Напомнянията за четене се управляват от устройството.",
    "openNotificationSettings": "Настройки за уведомяване",
    "review": "Оставете отзив",
    "question": "Въпрос",
    "of": "на"
  },
  "sr": {
    "appSettings": "Подешавања апликације",
    "settingsHint": "Изаберите језик интерфејса, тему и позадину. Подешавања се аутоматски чувају.",
    "background": "Позадина апликације",
    "addBook": "Додај књигу",
    "editBook": "Уреди књигу",
    "titlePlaceholder": "Унесите наслов књиге",
    "todayHint": "Иди на данас",
    "selectedFuture": "Можете погледати овај дан, али странице се могу унети само за данас или прошле дане.",
    "backToLibrary": "Назад у библиотеку",
    "bookCompleted": "Књига завршена!",
    "quizCreating": "Креирање квиза",
    "quizWait": "Сачекајте док се провере информације о књизи.",
    "quizError": "За овај наслов није могао да се направи поуздан квиз. Проверите наслов и интернет везу.",
    "next": "Следеће питање",
    "finish": "Заврши тест",
    "hint": "Хинт",
    "passed": "Тест је прошао!",
    "failed": "Тест није прошао",
    "result": "Резултат",
    "retry": "Покушајте поново",
    "developerMode": "Режим програмера",
    "developerSaved": "Режим програмера је сачуван на овом уређају.",
    "exitDeveloper": "Изађите из режима програмера",
    "developerPassword": "Лозинка програмера",
    "unlock": "Откључај",
    "wrongPassword": "Погрешна лозинка",
    "notificationsInfo": "Подсетнике за читање контролише уређај.",
    "openNotificationSettings": "Подешавања обавештења",
    "review": "Оставите рецензију",
    "question": "Питање",
    "of": "оф"
  },
  "hr": {
    "appSettings": "Postavke aplikacije",
    "settingsHint": "Odaberite jezik sučelja, temu i pozadinu. Postavke se automatski spremaju.",
    "background": "Pozadina aplikacije",
    "addBook": "Dodaj knjigu",
    "editBook": "Uredi knjigu",
    "titlePlaceholder": "Unesite naslov knjige",
    "todayHint": "Idi na danas",
    "selectedFuture": "Možete vidjeti ovaj dan, ali stranice možete unijeti samo za danas ili prošle dane.",
    "backToLibrary": "Natrag u knjižnicu",
    "bookCompleted": "Knjiga dovršena!",
    "quizCreating": "Izrada kviza",
    "quizWait": "Pričekajte dok se podaci o knjizi provjere.",
    "quizError": "Za ovaj naslov nije moguće izraditi pouzdani kviz. Provjerite naslov i internetsku vezu.",
    "next": "Sljedeće pitanje",
    "finish": "Završi test",
    "hint": "Savjet",
    "passed": "Test prošao!",
    "failed": "Test nije prošao",
    "result": "Rezultat",
    "retry": "Pokušajte ponovno",
    "developerMode": "Način rada za razvojne programere",
    "developerSaved": "Način rada razvojnog programera spremljen je na ovom uređaju.",
    "exitDeveloper": "Izađite iz moda razvojnog programera",
    "developerPassword": "Lozinka programera",
    "unlock": "Otključaj",
    "wrongPassword": "Pogrešna lozinka",
    "notificationsInfo": "Podsjetnike za čitanje kontrolira uređaj.",
    "openNotificationSettings": "Postavke obavijesti",
    "review": "Ostavite recenziju",
    "question": "Pitanje",
    "of": "od"
  },
  "lt": {
    "appSettings": "Programos nustatymai",
    "settingsHint": "Pasirinkite sąsajos kalbą, temą ir foną. Nustatymai išsaugomi automatiškai.",
    "background": "Programos fonas",
    "addBook": "Pridėti knygą",
    "editBook": "Redaguoti knygą",
    "titlePlaceholder": "Įveskite knygos pavadinimą",
    "todayHint": "Eikite į šiandieną",
    "selectedFuture": "Galite peržiūrėti šią dieną, tačiau puslapius galima įvesti tik apie šiandieną arba praėjusias dienas.",
    "backToLibrary": "Atgal į biblioteką",
    "bookCompleted": "Knyga baigta!",
    "quizCreating": "Viktorinos kūrimas",
    "quizWait": "Palaukite, kol bus patikrinta knygos informacija.",
    "quizError": "Nepavyko sukurti patikimos viktorinos šiam pavadinimui. Patikrinkite pavadinimą ir interneto ryšį.",
    "next": "Kitas klausimas",
    "finish": "Baigti testą",
    "hint": "Užuomina",
    "passed": "Testas išlaikytas!",
    "failed": "Testas neišlaikytas",
    "result": "Rezultatas",
    "retry": "Bandykite dar kartą",
    "developerMode": "Kūrėjo režimas",
    "developerSaved": "Kūrėjo režimas išsaugotas šiame įrenginyje.",
    "exitDeveloper": "Išeikite iš kūrėjo režimo",
    "developerPassword": "Kūrėjo slaptažodis",
    "unlock": "Atrakinti",
    "wrongPassword": "Neteisingas slaptažodis",
    "notificationsInfo": "Skaitymo priminimus valdo įrenginys.",
    "openNotificationSettings": "Pranešimų nustatymai",
    "review": "Palikite atsiliepimą",
    "question": "Klausimas",
    "of": "iš"
  },
  "lv": {
    "appSettings": "Lietotņu iestatījumi",
    "settingsHint": "Izvēlieties interfeisa valodu, motīvu un fonu. Iestatījumi tiek saglabāti automātiski.",
    "background": "Lietotnes fons",
    "addBook": "Pievienot grāmatu",
    "editBook": "Rediģēt grāmatu",
    "titlePlaceholder": "Ievadiet grāmatas nosaukumu",
    "todayHint": "Iet uz šodienu",
    "selectedFuture": "Varat skatīt šo dienu, bet lapas var ievadīt tikai par šodienu vai iepriekšējām dienām.",
    "backToLibrary": "Atpakaļ uz bibliotēku",
    "bookCompleted": "Grāmata pabeigta!",
    "quizCreating": "Viktorīnas izveide",
    "quizWait": "Lūdzu, uzgaidiet, kamēr tiek pārbaudīta grāmatas informācija.",
    "quizError": "Šim nosaukumam nevarēja izveidot uzticamu viktorīnu. Pārbaudiet nosaukumu un interneta savienojumu.",
    "next": "Nākamais jautājums",
    "finish": "Pabeigt testu",
    "hint": "Padoms",
    "passed": "Pārbaudījums nokārtots!",
    "failed": "Pārbaudījums nav nokārtots",
    "result": "Rezultāts",
    "retry": "Mēģiniet vēlreiz",
    "developerMode": "Izstrādātāja režīms",
    "developerSaved": "Šajā ierīcē ir saglabāts izstrādātāja režīms.",
    "exitDeveloper": "Izejiet no izstrādātāja režīma",
    "developerPassword": "Izstrādātāja parole",
    "unlock": "Atbloķēt",
    "wrongPassword": "Nepareiza parole",
    "notificationsInfo": "Lasīšanas atgādinājumus kontrolē ierīce.",
    "openNotificationSettings": "Paziņojumu iestatījumi",
    "review": "Atstājiet atsauksmi",
    "question": "Jautājums",
    "of": "no"
  },
  "et": {
    "appSettings": "Rakenduse seaded",
    "settingsHint": "Valige liidese keel, teema ja taust. Seaded salvestatakse automaatselt.",
    "background": "Rakenduse taust",
    "addBook": "Lisa raamat",
    "editBook": "Redigeeri raamatut",
    "titlePlaceholder": "Sisestage raamatu pealkiri",
    "todayHint": "Mine tänasesse päeva",
    "selectedFuture": "Seda päeva saate vaadata, kuid lehti saab sisestada ainult tänase või möödunud päevade kohta.",
    "backToLibrary": "Tagasi raamatukogusse",
    "bookCompleted": "Raamat valmis!",
    "quizCreating": "Viktoriini koostamine",
    "quizWait": "Palun oodake, kuni raamatuteavet kontrollitakse.",
    "quizError": "Selle pealkirja jaoks ei saanud usaldusväärset viktoriini luua. Kontrollige pealkirja ja Interneti-ühendust.",
    "next": "Järgmine küsimus",
    "finish": "Lõpeta test",
    "hint": "Vihje",
    "passed": "Test läbitud!",
    "failed": "Testi ei sooritatud",
    "result": "Tulemus",
    "retry": "Proovi uuesti",
    "developerMode": "Arendaja režiim",
    "developerSaved": "Sellesse seadmesse on salvestatud arendajarežiim.",
    "exitDeveloper": "Välju arendajarežiimist",
    "developerPassword": "Arendaja parool",
    "unlock": "Avage lukustus",
    "wrongPassword": "Vale parool",
    "notificationsInfo": "Meeldetuletuste lugemist juhib seade.",
    "openNotificationSettings": "Teavituste seaded",
    "review": "Jäta arvustus",
    "question": "küsimus",
    "of": "kohta"
  },
  "sl": {
    "appSettings": "Nastavitve aplikacije",
    "settingsHint": "Izberite jezik vmesnika, temo in ozadje. Nastavitve se samodejno shranijo.",
    "background": "Ozadje aplikacije",
    "addBook": "Dodaj knjigo",
    "editBook": "Uredi knjigo",
    "titlePlaceholder": "Vnesite naslov knjige",
    "todayHint": "Pojdi na danes",
    "selectedFuture": "Ta dan si lahko ogledate, vendar strani lahko vnesete samo za danes ali pretekle dni.",
    "backToLibrary": "Nazaj v knjižnico",
    "bookCompleted": "Knjiga dokončana!",
    "quizCreating": "Ustvarjanje kviza",
    "quizWait": "Počakajte, da se preverijo podatki o knjigi.",
    "quizError": "Za ta naslov ni bilo mogoče ustvariti zanesljivega kviza. Preverite naslov in internetno povezavo.",
    "next": "Naslednje vprašanje",
    "finish": "Končaj test",
    "hint": "Namig",
    "passed": "Test opravljen!",
    "failed": "Test ni opravljen",
    "result": "Rezultat",
    "retry": "poskusi ponovno",
    "developerMode": "Način za razvijalce",
    "developerSaved": "Način za razvijalce je shranjen v tej napravi.",
    "exitDeveloper": "Zapustite razvijalski način",
    "developerPassword": "Geslo razvijalca",
    "unlock": "Odkleni",
    "wrongPassword": "Napačno geslo",
    "notificationsInfo": "Opomnike za branje nadzira naprava.",
    "openNotificationSettings": "Nastavitve obvestil",
    "review": "Pusti oceno",
    "question": "vprašanje",
    "of": "od"
  },
  "ca": {
    "appSettings": "Configuració de l'aplicació",
    "settingsHint": "Trieu l'idioma, el tema i el fons de la interfície. La configuració es desa automàticament.",
    "background": "Fons de l'aplicació",
    "addBook": "Afegeix llibre",
    "editBook": "Edita el llibre",
    "titlePlaceholder": "Introduïu el títol del llibre",
    "todayHint": "Anar a avui",
    "selectedFuture": "Podeu veure aquest dia, però només es poden introduir pàgines per a dies d'avui o passats.",
    "backToLibrary": "Torna a la biblioteca",
    "bookCompleted": "Llibre completat!",
    "quizCreating": "Creació del qüestionari",
    "quizWait": "Espereu mentre es revisa la informació del llibre.",
    "quizError": "No s'ha pogut crear un qüestionari fiable per a aquest títol. Comproveu el títol i la connexió a Internet.",
    "next": "Següent pregunta",
    "finish": "Acaba la prova",
    "hint": "Pista",
    "passed": "Prova superada!",
    "failed": "Prova no superada",
    "result": "Resultat",
    "retry": "Torna-ho a provar",
    "developerMode": "Mode de desenvolupador",
    "developerSaved": "El mode de desenvolupador està desat en aquest dispositiu.",
    "exitDeveloper": "Sortiu del mode de desenvolupador",
    "developerPassword": "Contrasenya del desenvolupador",
    "unlock": "Desbloqueja",
    "wrongPassword": "Contrasenya incorrecta",
    "notificationsInfo": "Els recordatoris de lectura estan controlats pel dispositiu.",
    "openNotificationSettings": "Configuració de notificacions",
    "review": "Deixa una ressenya",
    "question": "Pregunta",
    "of": "de"
  },
  "sw": {
    "appSettings": "Mipangilio ya programu",
    "settingsHint": "Chagua lugha ya kiolesura, mandhari na usuli. Mipangilio huhifadhiwa kiotomatiki.",
    "background": "Mandharinyuma ya programu",
    "addBook": "Ongeza kitabu",
    "editBook": "Badilisha kitabu",
    "titlePlaceholder": "Weka kichwa cha kitabu",
    "todayHint": "Nenda kwa leo",
    "selectedFuture": "Unaweza kutazama siku hii, lakini kurasa zinaweza tu kuandikwa za leo au siku zilizopita.",
    "backToLibrary": "Rudi kwenye maktaba",
    "bookCompleted": "Kitabu kimekamilika!",
    "quizCreating": "Kuunda jaribio",
    "quizWait": "Tafadhali subiri wakati maelezo ya kitabu yanakaguliwa.",
    "quizError": "Maswali ya kuaminika hayakuweza kuundwa kwa mada hii. Angalia kichwa na muunganisho wa intaneti.",
    "next": "Swali linalofuata",
    "finish": "Maliza mtihani",
    "hint": "Kidokezo",
    "passed": "Mtihani umepita!",
    "failed": "Mtihani haujafaulu",
    "result": "Matokeo",
    "retry": "Jaribu tena",
    "developerMode": "Hali ya msanidi",
    "developerSaved": "Hali ya msanidi imehifadhiwa kwenye kifaa hiki.",
    "exitDeveloper": "Ondoka kwenye hali ya msanidi",
    "developerPassword": "Nenosiri la msanidi programu",
    "unlock": "Fungua",
    "wrongPassword": "Nenosiri si sahihi",
    "notificationsInfo": "Vikumbusho vya kusoma vinadhibitiwa na kifaa.",
    "openNotificationSettings": "Mipangilio ya arifa",
    "review": "Acha ukaguzi",
    "question": "Swali",
    "of": "ya"
  },
  "ta": {
    "appSettings": "பயன்பாட்டு அமைப்புகள்",
    "settingsHint": "இடைமுக மொழி, தீம் மற்றும் பின்னணியைத் தேர்ந்தெடுக்கவும். அமைப்புகள் தானாகவே சேமிக்கப்படும்.",
    "background": "பயன்பாட்டின் பின்னணி",
    "addBook": "புத்தகத்தைச் சேர்க்கவும்",
    "editBook": "புத்தகத்தைத் திருத்து",
    "titlePlaceholder": "புத்தகத்தின் தலைப்பை உள்ளிடவும்",
    "todayHint": "இன்று செல்லுங்கள்",
    "selectedFuture": "இந்த நாளை நீங்கள் பார்க்கலாம், ஆனால் இன்று அல்லது கடந்த நாட்களுக்கு மட்டுமே பக்கங்களை உள்ளிட முடியும்.",
    "backToLibrary": "நூலகத்திற்குத் திரும்பு",
    "bookCompleted": "புத்தகம் முடிந்தது!",
    "quizCreating": "வினாடி வினாவை உருவாக்குதல்",
    "quizWait": "புத்தகத் தகவல் சரிபார்க்கப்படும் வரை காத்திருக்கவும்.",
    "quizError": "இந்தத் தலைப்புக்கு நம்பகமான வினாடி வினாவை உருவாக்க முடியவில்லை. தலைப்பு மற்றும் இணைய இணைப்பைச் சரிபார்க்கவும்.",
    "next": "அடுத்த கேள்வி",
    "finish": "சோதனையை முடிக்கவும்",
    "hint": "குறிப்பு",
    "passed": "தேர்வில் தேர்ச்சி!",
    "failed": "தேர்வில் தேர்ச்சி பெறவில்லை",
    "result": "முடிவு",
    "retry": "மீண்டும் முயற்சிக்கவும்",
    "developerMode": "டெவலப்பர் பயன்முறை",
    "developerSaved": "இந்தச் சாதனத்தில் டெவலப்பர் பயன்முறை சேமிக்கப்பட்டுள்ளது.",
    "exitDeveloper": "டெவலப்பர் பயன்முறையிலிருந்து வெளியேறு",
    "developerPassword": "டெவலப்பர் கடவுச்சொல்",
    "unlock": "திறக்கவும்",
    "wrongPassword": "தவறான கடவுச்சொல்",
    "notificationsInfo": "வாசிப்பு நினைவூட்டல்கள் சாதனத்தால் கட்டுப்படுத்தப்படுகின்றன.",
    "openNotificationSettings": "அறிவிப்பு அமைப்புகள்",
    "review": "ஒரு மதிப்பாய்வை விடுங்கள்",
    "question": "கேள்வி",
    "of": "இன்"
  },
  "te": {
    "appSettings": "యాప్ సెట్టింగ్‌లు",
    "settingsHint": "ఇంటర్ఫేస్ భాష, థీమ్ మరియు నేపథ్యాన్ని ఎంచుకోండి. సెట్టింగ్‌లు స్వయంచాలకంగా సేవ్ చేయబడతాయి.",
    "background": "యాప్ నేపథ్యం",
    "addBook": "పుస్తకాన్ని జోడించండి",
    "editBook": "పుస్తకాన్ని సవరించండి",
    "titlePlaceholder": "పుస్తకం శీర్షికను నమోదు చేయండి",
    "todayHint": "ఈరోజుకి వెళ్ళండి",
    "selectedFuture": "మీరు ఈ రోజును వీక్షించవచ్చు, కానీ ఈ రోజు లేదా గత రోజులకు మాత్రమే పేజీలను నమోదు చేయవచ్చు.",
    "backToLibrary": "తిరిగి లైబ్రరీకి",
    "bookCompleted": "పుస్తకం పూర్తయింది!",
    "quizCreating": "క్విజ్‌ని సృష్టిస్తోంది",
    "quizWait": "దయచేసి పుస్తకం సమాచారం తనిఖీ చేయబడే వరకు వేచి ఉండండి.",
    "quizError": "ఈ శీర్షిక కోసం నమ్మదగిన క్విజ్‌ని సృష్టించడం సాధ్యపడలేదు. శీర్షిక మరియు ఇంటర్నెట్ కనెక్షన్‌ని తనిఖీ చేయండి.",
    "next": "తదుపరి ప్రశ్న",
    "finish": "పరీక్షను ముగించు",
    "hint": "సూచన",
    "passed": "పరీక్ష ఉత్తీర్ణత!",
    "failed": "పరీక్ష పాస్ కాలేదు",
    "result": "ఫలితం",
    "retry": "మళ్లీ ప్రయత్నించండి",
    "developerMode": "డెవలపర్ మోడ్",
    "developerSaved": "డెవలపర్ మోడ్ ఈ పరికరంలో సేవ్ చేయబడింది.",
    "exitDeveloper": "డెవలపర్ మోడ్ నుండి నిష్క్రమించండి",
    "developerPassword": "డెవలపర్ పాస్వర్డ్",
    "unlock": "అన్‌లాక్ చేయండి",
    "wrongPassword": "తప్పు పాస్‌వర్డ్",
    "notificationsInfo": "రీడింగ్ రిమైండర్‌లు పరికరం ద్వారా నియంత్రించబడతాయి.",
    "openNotificationSettings": "నోటిఫికేషన్ సెట్టింగ్‌లు",
    "review": "సమీక్షను వదిలివేయండి",
    "question": "ప్రశ్న",
    "of": "యొక్క"
  },
  "mr": {
    "appSettings": "ॲप सेटिंग्ज",
    "settingsHint": "इंटरफेस भाषा, थीम आणि पार्श्वभूमी निवडा. सेटिंग्ज आपोआप सेव्ह केल्या जातात.",
    "background": "ॲप पार्श्वभूमी",
    "addBook": "पुस्तक जोडा",
    "editBook": "पुस्तक संपादित करा",
    "titlePlaceholder": "पुस्तकाचे शीर्षक प्रविष्ट करा",
    "todayHint": "आज जा",
    "selectedFuture": "आपण हा दिवस पाहू शकता, परंतु पृष्ठे फक्त आज किंवा मागील दिवसांसाठी प्रविष्ट केली जाऊ शकतात.",
    "backToLibrary": "लायब्ररीकडे परत",
    "bookCompleted": "पुस्तक पूर्ण झाले!",
    "quizCreating": "क्विझ तयार करत आहे",
    "quizWait": "कृपया पुस्तक माहिती तपासली जाईपर्यंत प्रतीक्षा करा.",
    "quizError": "या शीर्षकासाठी विश्वसनीय प्रश्नमंजुषा तयार करता आली नाही. शीर्षक आणि इंटरनेट कनेक्शन तपासा.",
    "next": "पुढचा प्रश्न",
    "finish": "चाचणी पूर्ण करा",
    "hint": "इशारा",
    "passed": "चाचणी उत्तीर्ण!",
    "failed": "चाचणी पास झाली नाही",
    "result": "परिणाम",
    "retry": "पुन्हा प्रयत्न करा",
    "developerMode": "विकसक मोड",
    "developerSaved": "विकसक मोड या डिव्हाइसवर सेव्ह केला आहे.",
    "exitDeveloper": "विकसक मोडमधून बाहेर पडा",
    "developerPassword": "विकसक पासवर्ड",
    "unlock": "अनलॉक करा",
    "wrongPassword": "चुकीचा पासवर्ड",
    "notificationsInfo": "वाचन स्मरणपत्रे डिव्हाइसद्वारे नियंत्रित केली जातात.",
    "openNotificationSettings": "सूचना सेटिंग्ज",
    "review": "एक पुनरावलोकन सोडा",
    "question": "प्रश्न",
    "of": "च्या"
  },
  "gu": {
    "appSettings": "એપ્લિકેશન સેટિંગ્સ",
    "settingsHint": "ઇન્ટરફેસ ભાષા, થીમ અને પૃષ્ઠભૂમિ પસંદ કરો. સેટિંગ્સ આપમેળે સાચવવામાં આવે છે.",
    "background": "એપ્લિકેશન પૃષ્ઠભૂમિ",
    "addBook": "પુસ્તક ઉમેરો",
    "editBook": "પુસ્તક સંપાદિત કરો",
    "titlePlaceholder": "પુસ્તકનું શીર્ષક દાખલ કરો",
    "todayHint": "આજે જાઓ",
    "selectedFuture": "તમે આ દિવસ જોઈ શકો છો, પરંતુ પૃષ્ઠો ફક્ત આજના અથવા પાછલા દિવસો માટે જ દાખલ કરી શકાય છે.",
    "backToLibrary": "પુસ્તકાલય પર પાછા",
    "bookCompleted": "પુસ્તક પૂર્ણ થયું!",
    "quizCreating": "ક્વિઝ બનાવી રહ્યા છીએ",
    "quizWait": "પુસ્તકની માહિતી તપાસવામાં આવે ત્યાં સુધી કૃપા કરીને રાહ જુઓ.",
    "quizError": "આ શીર્ષક માટે વિશ્વસનીય ક્વિઝ બનાવી શકાઈ નથી. શીર્ષક અને ઇન્ટરનેટ કનેક્શન તપાસો.",
    "next": "આગળનો પ્રશ્ન",
    "finish": "પરીક્ષણ સમાપ્ત કરો",
    "hint": "સંકેત",
    "passed": "ટેસ્ટ પાસ!",
    "failed": "પરીક્ષા પાસ થઈ નથી",
    "result": "પરિણામ",
    "retry": "ફરી પ્રયાસ કરો",
    "developerMode": "વિકાસકર્તા મોડ",
    "developerSaved": "આ ઉપકરણ પર વિકાસકર્તા મોડ સાચવેલ છે.",
    "exitDeveloper": "વિકાસકર્તા મોડમાંથી બહાર નીકળો",
    "developerPassword": "વિકાસકર્તા પાસવર્ડ",
    "unlock": "અનલોક કરો",
    "wrongPassword": "ખોટો પાસવર્ડ",
    "notificationsInfo": "રીડિંગ રીમાઇન્ડર્સ ઉપકરણ દ્વારા નિયંત્રિત થાય છે.",
    "openNotificationSettings": "સૂચના સેટિંગ્સ",
    "review": "એક સમીક્ષા છોડો",
    "question": "પ્રશ્ન",
    "of": "ના"
  },
  "kn": {
    "appSettings": "ಅಪ್ಲಿಕೇಶನ್ ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    "settingsHint": "ಇಂಟರ್ಫೇಸ್ ಭಾಷೆ, ಥೀಮ್ ಮತ್ತು ಹಿನ್ನೆಲೆ ಆಯ್ಕೆಮಾಡಿ. ಸೆಟ್ಟಿಂಗ್‌ಗಳನ್ನು ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಉಳಿಸಲಾಗುತ್ತದೆ.",
    "background": "ಅಪ್ಲಿಕೇಶನ್ ಹಿನ್ನೆಲೆ",
    "addBook": "ಪುಸ್ತಕವನ್ನು ಸೇರಿಸಿ",
    "editBook": "ಪುಸ್ತಕ ಸಂಪಾದಿಸಿ",
    "titlePlaceholder": "ಪುಸ್ತಕದ ಶೀರ್ಷಿಕೆಯನ್ನು ನಮೂದಿಸಿ",
    "todayHint": "ಇವತ್ತಿಗೆ ಹೋಗು",
    "selectedFuture": "ನೀವು ಈ ದಿನವನ್ನು ವೀಕ್ಷಿಸಬಹುದು, ಆದರೆ ಪುಟಗಳನ್ನು ಇಂದು ಅಥವಾ ಹಿಂದಿನ ದಿನಗಳಿಗೆ ಮಾತ್ರ ನಮೂದಿಸಬಹುದು.",
    "backToLibrary": "ಗ್ರಂಥಾಲಯಕ್ಕೆ ಹಿಂತಿರುಗಿ",
    "bookCompleted": "ಪುಸ್ತಕ ಪೂರ್ಣಗೊಂಡಿದೆ!",
    "quizCreating": "ರಸಪ್ರಶ್ನೆ ರಚಿಸಲಾಗುತ್ತಿದೆ",
    "quizWait": "ಪುಸ್ತಕದ ಮಾಹಿತಿಯನ್ನು ಪರಿಶೀಲಿಸುವವರೆಗೆ ದಯವಿಟ್ಟು ನಿರೀಕ್ಷಿಸಿ.",
    "quizError": "ಈ ಶೀರ್ಷಿಕೆಗಾಗಿ ವಿಶ್ವಾಸಾರ್ಹ ರಸಪ್ರಶ್ನೆಯನ್ನು ರಚಿಸಲಾಗಲಿಲ್ಲ. ಶೀರ್ಷಿಕೆ ಮತ್ತು ಇಂಟರ್ನೆಟ್ ಸಂಪರ್ಕವನ್ನು ಪರಿಶೀಲಿಸಿ.",
    "next": "ಮುಂದಿನ ಪ್ರಶ್ನೆ",
    "finish": "ಪರೀಕ್ಷೆಯನ್ನು ಮುಗಿಸಿ",
    "hint": "ಸುಳಿವು",
    "passed": "ಪರೀಕ್ಷೆ ಪಾಸಾಗಿದೆ!",
    "failed": "ಪರೀಕ್ಷೆ ಪಾಸಾಗಿಲ್ಲ",
    "result": "ಫಲಿತಾಂಶ",
    "retry": "ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ",
    "developerMode": "ಡೆವಲಪರ್ ಮೋಡ್",
    "developerSaved": "ಈ ಸಾಧನದಲ್ಲಿ ಡೆವಲಪರ್ ಮೋಡ್ ಅನ್ನು ಉಳಿಸಲಾಗಿದೆ.",
    "exitDeveloper": "ಡೆವಲಪರ್ ಮೋಡ್‌ನಿಂದ ನಿರ್ಗಮಿಸಿ",
    "developerPassword": "ಡೆವಲಪರ್ ಪಾಸ್ವರ್ಡ್",
    "unlock": "ಅನ್ಲಾಕ್ ಮಾಡಿ",
    "wrongPassword": "ತಪ್ಪಾದ ಗುಪ್ತಪದ",
    "notificationsInfo": "ಓದುವ ಜ್ಞಾಪನೆಗಳನ್ನು ಸಾಧನದಿಂದ ನಿಯಂತ್ರಿಸಲಾಗುತ್ತದೆ.",
    "openNotificationSettings": "ಅಧಿಸೂಚನೆ ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    "review": "ವಿಮರ್ಶೆಯನ್ನು ಬಿಡಿ",
    "question": "ಪ್ರಶ್ನೆ",
    "of": "ನ"
  },
  "ml": {
    "appSettings": "ആപ്പ് ക്രമീകരണങ്ങൾ",
    "settingsHint": "ഇൻ്റർഫേസ് ഭാഷ, തീം, പശ്ചാത്തലം എന്നിവ തിരഞ്ഞെടുക്കുക. ക്രമീകരണങ്ങൾ സ്വയമേവ സംരക്ഷിക്കപ്പെടുന്നു.",
    "background": "ആപ്പ് പശ്ചാത്തലം",
    "addBook": "പുസ്തകം ചേർക്കുക",
    "editBook": "പുസ്തകം എഡിറ്റ് ചെയ്യുക",
    "titlePlaceholder": "പുസ്തകത്തിൻ്റെ പേര് നൽകുക",
    "todayHint": "ഇന്ന് പോകൂ",
    "selectedFuture": "നിങ്ങൾക്ക് ഈ ദിവസം കാണാൻ കഴിയും, എന്നാൽ ഇന്നത്തെ അല്ലെങ്കിൽ കഴിഞ്ഞ ദിവസങ്ങളിൽ മാത്രമേ പേജുകൾ നൽകാനാകൂ.",
    "backToLibrary": "ലൈബ്രറിയിലേക്ക് മടങ്ങുക",
    "bookCompleted": "പുസ്തകം പൂർത്തിയായി!",
    "quizCreating": "ക്വിസ് സൃഷ്ടിക്കുന്നു",
    "quizWait": "ബുക്ക് വിവരങ്ങൾ പരിശോധിക്കുമ്പോൾ കാത്തിരിക്കുക.",
    "quizError": "ഈ ശീർഷകത്തിനായി വിശ്വസനീയമായ ഒരു ക്വിസ് സൃഷ്ടിക്കാൻ കഴിഞ്ഞില്ല. ശീർഷകവും ഇൻ്റർനെറ്റ് കണക്ഷനും പരിശോധിക്കുക.",
    "next": "അടുത്ത ചോദ്യം",
    "finish": "പരീക്ഷ പൂർത്തിയാക്കുക",
    "hint": "സൂചന",
    "passed": "ടെസ്റ്റ് പാസ്സായി!",
    "failed": "ടെസ്റ്റ് വിജയിച്ചില്ല",
    "result": "ഫലം",
    "retry": "വീണ്ടും ശ്രമിക്കുക",
    "developerMode": "ഡെവലപ്പർ മോഡ്",
    "developerSaved": "ഈ ഉപകരണത്തിൽ ഡെവലപ്പർ മോഡ് സംരക്ഷിച്ചിരിക്കുന്നു.",
    "exitDeveloper": "ഡെവലപ്പർ മോഡിൽ നിന്ന് പുറത്തുകടക്കുക",
    "developerPassword": "ഡെവലപ്പർ പാസ്വേഡ്",
    "unlock": "അൺലോക്ക് ചെയ്യുക",
    "wrongPassword": "തെറ്റായ പാസ്‌വേഡ്",
    "notificationsInfo": "റീഡിംഗ് റിമൈൻഡറുകൾ ഉപകരണം നിയന്ത്രിക്കുന്നു.",
    "openNotificationSettings": "അറിയിപ്പ് ക്രമീകരണങ്ങൾ",
    "review": "ഒരു അവലോകനം വിടുക",
    "question": "ചോദ്യം",
    "of": "ൻ്റെ"
  },
  "ne": {
    "appSettings": "एप सेटिङहरू",
    "settingsHint": "इन्टरफेस भाषा, विषयवस्तु र पृष्ठभूमि छान्नुहोस्। सेटिङहरू स्वचालित रूपमा सुरक्षित हुन्छन्।",
    "background": "अनुप्रयोग पृष्ठभूमि",
    "addBook": "पुस्तक थप्नुहोस्",
    "editBook": "पुस्तक सम्पादन गर्नुहोस्",
    "titlePlaceholder": "पुस्तक शीर्षक प्रविष्ट गर्नुहोस्",
    "todayHint": "आज जानुहोस्",
    "selectedFuture": "तपाईं यो दिन हेर्न सक्नुहुन्छ, तर पृष्ठहरू आज वा विगतका दिनहरूका लागि मात्र प्रविष्ट गर्न सकिन्छ।",
    "backToLibrary": "पुस्तकालय मा फर्कनुहोस्",
    "bookCompleted": "पुस्तक पूरा भयो!",
    "quizCreating": "क्विज सिर्जना गर्दै",
    "quizWait": "कृपया पुस्तक जानकारी जाँच हुँदा पर्खनुहोस्।",
    "quizError": "यो शीर्षकको लागि भरपर्दो क्विज सिर्जना गर्न सकिएन। शीर्षक र इन्टरनेट जडान जाँच गर्नुहोस्।",
    "next": "अर्को प्रश्न",
    "finish": "परीक्षण समाप्त गर्नुहोस्",
    "hint": "संकेत",
    "passed": "परीक्षा पास भयो!",
    "failed": "परीक्षा पास भएन",
    "result": "नतिजा",
    "retry": "पुन: प्रयास गर्नुहोस्",
    "developerMode": "विकासकर्ता मोड",
    "developerSaved": "यस यन्त्रमा विकासकर्ता मोड सुरक्षित गरिएको छ।",
    "exitDeveloper": "विकासकर्ता मोडबाट बाहिर निस्कनुहोस्",
    "developerPassword": "विकासकर्ता पासवर्ड",
    "unlock": "अनलक गर्नुहोस्",
    "wrongPassword": "गलत पासवर्ड",
    "notificationsInfo": "पढ्ने रिमाइन्डरहरू उपकरणद्वारा नियन्त्रण गरिन्छ।",
    "openNotificationSettings": "सूचना सेटिङहरू",
    "review": "एक समीक्षा छोड्नुहोस्",
    "question": "प्रश्न",
    "of": "को"
  }
};
